SET @sPluginName = 'aqb_points';
SET @sPluginTitle = 'Global Points System';

SET @iOrder = (SELECT MAX(`order`) FROM `sys_menu_admin` WHERE `parent_id`='2');
INSERT INTO `sys_menu_admin`(`parent_id`, `name`, `title`, `url`, `description`, `icon`, `icon_large`, `check`, `order`) VALUES
(2, @sPluginName, '_aqb_points_admin', '{siteUrl}modules/?r=aqb_points/administration/', 'Global Points System admin panel', 'modules/aqb/points/|points_menu_icon.png', '', '', @iOrder + 1);

INSERT INTO `sys_permalinks`(`standard`, `permalink`, `check`) VALUES
('modules/?r=aqb_points/', 'm/aqb_points/', 'permalinks_module_aqb_points');

SET @iMaxOrder = (SELECT `menu_order` + 1 FROM `sys_options_cats` ORDER BY `menu_order` DESC LIMIT 1);
INSERT INTO `sys_options_cats` (`name`, `menu_order`) VALUES (@sPluginTitle, @iMaxOrder);
SET @iCategId = (SELECT LAST_INSERT_ID());
INSERT INTO `sys_options` (`Name`, `VALUE`, `kateg`, `desc`, `Type`, `check`, `err_text`, `order_in_kateg`) VALUES
('permalinks_module_aqb_points', 'on', @iCategId, 'Enable friendly permalinks in Global Points System', 'checkbox', '', '', 0),
('aqb_points_page_price', '0.6', @iCategId, 'Price for one point', 'digit', '', '', 1),
('aqb_points_page_num_history', '10', @iCategId, 'Number of records on history page', 'digit', '', '', 2),
('aqb_points_page_num_leaders_block', '10', @iCategId, 'Number of members in leaders block', 'digit', '', '', 3),
('aqb_points_page_num_leaders_page', '50', @iCategId, 'Number of members on leaders page', 'digit', '', '', 4),
('aqb_points_enable_increment', 'on', @iCategId, 'Enable Increment for membership levels', 'checkbox', '', '', 5),
('aqb_points_enable_present_points', 'on', @iCategId, 'Enable present Points feature', 'checkbox', '', '', 6),
('aqb_points_enable_points_info', 'on', @iCategId, 'Enable points info for members', 'checkbox', '', '', 7),
('aqb_points_enable_mail_send_penalty', 'on', @iCategId, 'Send email to a member about penalized points', 'checkbox', '', '', 9),
('aqb_points_enable_mail_send_present', 'on', @iCategId, 'Send email to a member about presented points', 'checkbox', '', '', 10),
('aqb_points_enable_exchange_points_to_cache', 'on', @iCategId, 'Enable exchange points to cache feature', 'checkbox', '', '', 11),
('aqb_points_excahnge_limit', '0', @iCategId, 'The minimum number of points to send exchange request (<b>0</b> - <b>no limit</b>)', 'digit', '', '', 12),
('aqb_price_to_excahnge', '0.01', @iCategId, 'Price for exchange point to cache(<b>price in currency for one point</b>)', 'digit', '', '', 13),
('aqb_points_levels_enabled', 'on', @iCategId, 'Enable levels feautre', 'checkbox', '', '', 14),
('aqb_points_levels_member_page_block', 'on', @iCategId, 'Enable levels block on account page', 'checkbox', '', '', 15),
('aqb_points_levels_profile_page_block', 'on', @iCategId, 'Enable levels block on profile page', 'checkbox', '', '', 16);


INSERT INTO `sys_options` (`Name`, `VALUE`, `kateg`, `desc`, `Type`, `check`, `err_text`, `order_in_kateg`) VALUES
('aqb_points_packages', '', 0, 'Contains points packages', 'text', '', '', NULL);

INSERT INTO `sys_email_templates` (`Name`,`Subject`,`Body`,`Desc`,`LangID`) VALUES
('t_AqbPointsPresent', 'You have got gift points', '<html><head></head><body style="font: 12px Verdana; color:#000000">\r\n<p><b>Dear <RealName></b>,</p>\r\n\r\n<p>You have got <PointsNum> points<PointsGiftReason> from <PointsSender>!</p>\r\n\r\n<p>Simply follow the link below to view your points history:<br /><a href="<PointsHistoryLink>"><PointsHistoryLink></a></p>\r\n\r\n<p><b>Thank you for using our services!</b></p>\r\n\r\n<p>--</p>\r\n<p style="font: bold 10px Verdana; color:red"><SiteName> mail delivery system!!!\r\n<br />Auto-generated e-mail, please, do not reply!!!</p></body></html>', '<font color="#769729">Received points email</font>', 0),
('t_AqbPointsPenalized', 'You were penalized with points', '<html><head></head><body style="font: 12px Verdana; color:#000000">\r\n<p><b>Dear <RealName></b>,</p>\r\n\r\n<p>You were penalized with <PointsNum> points<PointsGiftReason> by site Administration!</p>\r\n\r\n<p>Simply follow the link below to view your points history:<br /><a href="<PointsHistoryLink>"><PointsHistoryLink></a></p>\r\n\r\n<p><b>Thank you for using our services!</b></p>\r\n\r\n<p>--</p>\r\n<p style="font: bold 10px Verdana; color:red"><SiteName> mail delivery system!!!\r\n<br />Auto-generated e-mail, please, do not reply!!!</p></body></html>', '<font color="#769729">Penalized points email</font>', 0),
('t_AqbPointsExchanged', 'Your points were exchanged to money', '<html><head></head><body style="font: 12px Verdana; color:#000000">\r\n<p><b>Dear <RealName></b>,</p>\r\n\r\n<p>Your points request was processed! <PointsNum> points were exchanged to <Sum> </p>\r\n\r\n<p>Simply follow the link below to view your points history:<br /><a href="<PointsHistoryLink>"><PointsHistoryLink></a></p>\r\n\r\n<p><b>Thank you for using our services!</b></p>\r\n\r\n<p>--</p>\r\n<p style="font: bold 10px Verdana; color:red"><SiteName> mail delivery system!!!\r\n<br />Auto-generated e-mail, please, do not reply!!!</p></body></html>', 'Exchange points to money template', 0);



CREATE TABLE IF NOT EXISTS `[db_prefix]memlevels_settings` (
  `id` int( 11 ) NOT NULL default '0',
  `increment` int( 11 ) NOT NULL default '0',
  `maximum` int( 11 ) NOT NULL default '0',
  `maximum_per_day` int( 11 ) NOT NULL default '0',
   PRIMARY KEY ( `id` )
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `[db_prefix]memlevels_pricing` (
  `id` int( 11 ) NOT NULL AUTO_INCREMENT ,
  `id_level` int( 11 ) NOT NULL default '0',
  `days` int( 11 ) NOT NULL default '0',
  `points` int( 11 ) NOT NULL default '0',
  PRIMARY KEY ( `id` ),
  UNIQUE KEY (`id_level`,`days`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `[db_prefix]history` (
  `id` int( 11 ) NOT NULL AUTO_INCREMENT,
  `action_id` int(11) NOT NULL default '0',
  `profile_id` int(11) NOT NULL default '0',
  `reason` varchar(255) NOT NULL default '',
  `points` bigint(20) NOT NULL default '0',
  `time` int(11) NOT NULL default '0',
   PRIMARY KEY  (`id`)
) ENGINE = MYISAM DEFAULT CHARSET = utf8;

CREATE TABLE `[db_prefix]transactions` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `price` float NOT NULL default '0',
  `status` enum('pending', 'active') NOT NULL default 'pending', 
  `type` enum('buy', 'exchange','package') NOT NULL default 'buy',  
  `date` int(11) unsigned default NULL,
  `date_end` int(11) unsigned NOT NULL default '0',
  `payment_date` int(11) unsigned NOT NULL default '0',
  `points_num` int( 11 ) NOT NULL default '0',
  `buyer_id` int( 11 ) NOT NULL default '0',
  `tnx` varchar(20) NOT NULL default '',
  `payment_status` varchar(10) NOT NULL default '',
  PRIMARY KEY (`id`)
) ENGINE = MYISAM DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `[db_prefix]levels` (
  `id` int( 11 ) NOT NULL AUTO_INCREMENT ,
  `title` varchar( 255 ) default NULL,
  `img` varchar( 20 ) NOT NULL default '',
  `date` int(11) NOT NULL default '0',
  `min` bigint(20) unsigned NOT NULL default '0',
  `max` bigint(20) unsigned NOT NULL default '0',
  `memlevel` varchar(10) NOT NULL default '',
  `bonus` bigint(20) unsigned NOT NULL default '0',
   PRIMARY KEY ( `id` )
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `[db_prefix]actions` (
  `id` int( 11 ) NOT NULL AUTO_INCREMENT ,
  `title` varchar( 255 ) default NULL,
  `description` varchar( 255 ) default NULL,
  `handler` varchar( 255 ) NOT NULL default '',
  `alerts_unit` varchar(128) NOT NULL default '',
  `points` int( 11 ) NOT NULL default '0',
  `day_limit` int( 11 ) NOT NULL default '0',
  `active` enum('true','false') NOT NULL default 'true',
  `module_uri` varchar(32) NOT NULL default '',
  `param` varchar(50) NOT NULL default 'second',
  `group` varchar( 50 ) default 'profile',
  `duplicated` tinyint(1) NOT NULL default '1',
   PRIMARY KEY ( `id` ),
   KEY `handler` (`handler`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

INSERT INTO `[db_prefix]actions` VALUES
(NULL, '_aqb_points_action_profile_join', '', 'join', 'profile', 2, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_login', '', 'login', 'profile', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_logout', '', 'logout', 'profile', -1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_edit', '', 'edit', 'profile', -1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_send_mail_internal', '', 'send_mail_internal', 'profile', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_send_mail_internal_recipient', '', 'send_mail_internal', 'profile', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_commentPost', '', 'commentPost', 'profile', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_commentRated', '', 'commentRated', 'profile', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_commentRemoved', '', 'commentRemoved', 'profile', -1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_commentUpdated', '', 'commentUpdated', 'profile', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_edit_status', '', 'edit_status', 'profile', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_status_message', '', 'edit_status_message', 'profile', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_friend_delete', '', 'delete', 'friend', -1, 100, 'true', '', 'second', 'friend', 1),
(NULL, '_aqb_points_action_friend_accept', '', 'accept', 'friend', 1, 100, 'true', '', 'second', 'friend', 1),
(NULL, '_aqb_points_action_friend_request', '', 'request', 'friend', 1, 100, 'true', '', 'second', 'friend', 1),
(NULL, '_aqb_points_action_friend_delete_recipient', '', 'delete', 'friend', -1, 100, 'true', '', 'first', 'friend', 1),
(NULL, '_aqb_points_action_friend_accept_recipient', '', 'accept', 'friend', 1, 100, 'true', '', 'first', 'friend', 1),
(NULL, '_aqb_points_action_friend_request_recipient', '', 'request', 'friend', 1, 100, 'true', '', 'first', 'friend', 1),
(NULL, '_aqb_points_action_profile_rate', '', 'rate', 'profile', 2, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_fave_add', '', 'add', 'fave', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_fave_delete', '', 'delete', 'fave', -1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_block_add', '', 'add', 'block', -1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_block_delete', '', 'delete', 'block', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_fave_add_recipient', '', 'add', 'fave', 1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_fave_delete_recipient', '', 'delete', 'fave', -1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_profile_block_add_recipient', '', 'add', 'block', -1, 100, 'true', '', 'first', 'profile', 0),
(NULL, '_aqb_points_action_profile_block_delete_recipient', '', 'delete', 'block', 1, 100, 'true', '', 'second', 'profile', 0),
(NULL, '_aqb_points_action_ads_edit', '', 'edit', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_create', '', 'create', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_delete', '', 'delete', 'ads', -1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_buy', '', 'buy', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_view', '', 'view', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_rate', '', 'rate', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_commentPost', '', 'commentPost', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_commentRated', '', 'commentRated', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_commentRemoved', '', 'commentRemoved', 'ads', -1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_ads_commentUpdated', '', 'commentUpdated', 'ads', 1, 100, 'true', 'ads', 'second', 'ads', 0),
(NULL, '_aqb_points_action_bx_articles_featured', '', 'featured', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 1),
(NULL, '_aqb_points_action_bx_articles_delete', '', 'delete', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 1),
(NULL, '_aqb_points_action_bx_articles_publish', '', 'publish', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 1),
(NULL, '_aqb_points_action_bx_articles_unpublish', '', 'unpublish', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 1),
(NULL, '_aqb_points_action_bx_articles_commentPost', '', 'commentPost', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_commentRated', '', 'commentRated', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_commentRemoved', '', 'commentRemoved', 'bx_articles', -1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_commentUpdated', '', 'commentUpdated', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_post', '', 'post', 'articles', -1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_edit', '', 'edit', 'articles', 1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_articles_rate', '', 'rate', 'bx_articles', 1, 100, 'true', 'articles', 'second', 'articles', 0),
(NULL, '_aqb_points_action_bx_avatar_add', '', 'add', 'bx_avatar', 1, 1000, 'true', 'avatar', 'second', 'avatar', 0),
(NULL, '_aqb_points_action_bx_avatar_change', '', 'change', 'bx_avatar', 1, 100, 'true', 'avatar', 'second', 'avatar', 0),
(NULL, '_aqb_points_action_bx_blogs_view_post', '', 'view_post', 'bx_blogs', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_create', '', 'create', 'bx_blogs', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_edit_post', '', 'edit_post', 'bx_blogs', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_delete_post', '', 'delete_post', 'bx_blogs', -1, 100, 'true', 'blogs', 'second', 'blogs', 1),
(NULL, '_aqb_points_action_bx_blogs_commentPost', '', 'commentPost', 'blogposts', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_commentRated', '', 'commentRated', 'blogposts', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_commentRemoved', '', 'commentRemoved', 'blogposts', -1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_commentUpdated', '', 'commentUpdated', 'blogposts', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_blogs_rate', '', 'rate', 'blogposts', 1, 100, 'true', 'blogs', 'second', 'blogs', 0),
(NULL, '_aqb_points_action_bx_events_join', '', 'join', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_add', '', 'add', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_join_request', '', 'join_request', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_join_reject', '', 'join_reject', 'bx_events', -1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_join_confirm', '', 'join_confirm', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_change', '', 'change', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_delete', '', 'delete', 'bx_events', -1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_fan_remove', '', 'fan_remove', 'bx_events', -1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_fan_become_admin', '', 'fan_become_admin', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_admin_become_fan', '', 'admin_become_fan', 'bx_events', -1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_mark_as_featured', '', 'mark_as_featured', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 1),
(NULL, '_aqb_points_action_bx_events_commentPost', '', 'commentPost', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_commentRated', '', 'commentRated', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_commentRemoved', '', 'commentRemoved', 'bx_events', -1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_commentUpdated', '', 'commentUpdated', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_events_rate', '', 'rate', 'bx_events', 1, 100, 'true', 'events', 'second', 'events', 0),
(NULL, '_aqb_points_action_bx_feedback_post', '', 'post', 'feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_edit', '', 'edit', 'feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_approve', '', 'approve', 'bx_feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 1),
(NULL, '_aqb_points_action_bx_feedback_reject', '', 'reject', 'bx_feedback', -1, 100, 'true', 'feedback', 'second', 'feedback', 1),
(NULL, '_aqb_points_action_bx_feedback_delete', '', 'delete', 'bx_feedback', -1, 100, 'true', 'feedback', 'second', 'feedback', 1),
(NULL, '_aqb_points_action_bx_feedback_commentPost', '', 'commentPost', 'bx_feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_commentRated', '', 'commentRated', 'bx_feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_commentRemoved', '', 'commentRemoved', 'bx_feedback', -1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_commentUpdated', '', 'commentUpdated', 'bx_feedback', 1, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_feedback_rate', '', 'rate', 'bx_feedback', 2, 100, 'true', 'feedback', 'second', 'feedback', 0),
(NULL, '_aqb_points_action_bx_files_add', '', 'add', 'bx_files', 1, 100, 'true', 'files', 'second', 'files', 1),
(NULL, '_aqb_points_action_bx_files_commentPost', '', 'commentPost', 'bx_files', 1, 100, 'true', 'files', 'second', 'files', 0),
(NULL, '_aqb_points_action_bx_files_commentRated', '', 'commentRated', 'bx_files', 1, 100, 'true', 'files', 'second', 'files', 0),
(NULL, '_aqb_points_action_bx_files_commentRemoved', '', 'commentRemoved', 'bx_files', -1, 100, 'true', 'files', 'second', 'files', 0),
(NULL, '_aqb_points_action_bx_files_commentUpdated', '', 'commentUpdated', 'bx_files', 1, 100, 'true', 'files', 'second', 'files', 0),
(NULL, '_aqb_points_action_bx_files_rate', '', 'rate', 'bx_files', 1, 100, 'true', 'files', 'second', 'files', 0),
(NULL, '_aqb_points_action_bx_files_delete', '', 'delete', 'bx_files', -1, 100, 'true', 'files', 'delete_media', 'files', 1),
(NULL, '_aqb_points_action_bx_forum_post', '', 'post', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_edit', '', 'edit', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_reply', '', 'reply', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_post_edit', '', 'post_edit', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_edit_del', '', 'edit_del', 'bx_forum', -1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_new_topic', '', 'new_topic', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_vote', '', 'vote', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_post_report', '', 'post_report', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_flag', '', 'flag', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_forum_unflag', '', 'unflag', 'bx_forum', 1, 100, 'true', 'forum', 'cookie', 'forum', 0),
(NULL, '_aqb_points_action_bx_groups_join', '', 'join', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_join_request', '', 'join_request', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_join_reject', '', 'join_reject', 'bx_groups', -1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_join_confirm', '', 'join_confirm', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_add', '', 'add', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_change', '', 'change', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_delete', '', 'delete', 'bx_groups', -1, 100, 'true', 'groups', 'second', 'groups', 1),
(NULL, '_aqb_points_action_bx_groups_fan_remove', '', 'fan_remove', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_fan_become_admin', '', 'fan_become_admin', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_admin_become_fan', '', 'admin_become_fan', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_mark_as_featured', '', 'mark_as_featured', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 1),
(NULL, '_aqb_points_action_bx_groups_commentPost', '', 'commentPost', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_commentRated', '', 'commentRated', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_commentRemoved', '', 'commentRemoved', 'bx_groups', -1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_commentUpdated', '', 'commentUpdated', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_groups_rate', '', 'rate', 'bx_groups', 1, 100, 'true', 'groups', 'second', 'groups', 0),
(NULL, '_aqb_points_action_bx_news_rate', '', 'rate', 'bx_news', 2, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_post', '', 'post', 'news', 1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_edit', '', 'edit', 'news', 1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_featured', '', 'featured', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 1),
(NULL, '_aqb_points_action_news_publish', '', 'publish', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 1),
(NULL, '_aqb_points_action_news_unpublish', '', 'unpublish', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 1),
(NULL, '_aqb_points_action_news_delete', '', 'delete', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 1),
(NULL, '_aqb_points_action_news_commentPost', '', 'commentPost', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_commentRemoved', '', 'commentRemoved', 'bx_news', -1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_commentUpdated', '', 'commentUpdated', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_news_commentRated', '', 'commentRated', 'bx_news', 1, 100, 'true', 'news', 'second', 'news', 0),
(NULL, '_aqb_points_action_bx_photos_add', '', 'add', 'bx_photos', 1, 100, 'true', 'photos', 'second', 'photos', 1),
(NULL, '_aqb_points_action_bx_photos_commentPost', '', 'commentPost', 'bx_photos', 1, 100, 'true', 'photos', 'second', 'photos', 0),
(NULL, '_aqb_points_action_bx_photos_commentRemoved', '', 'commentRemoved', 'bx_photos', -1, 100, 'true', 'photos', 'second', 'photos', 0),
(NULL, '_aqb_points_action_bx_photos_commentUpdated', '', 'commentUpdated', 'bx_photos', 1, 100, 'true', 'photos', 'second', 'photos', 0),
(NULL, '_aqb_points_action_bx_photos_commentRated', '', 'commentRated', 'bx_photos', 1, 100, 'true', 'photos', 'second', 'photos', 0),
(NULL, '_aqb_points_action_bx_photos_rate', '', 'rate', 'bx_photos', 1, 100, 'true', 'photos', 'second', 'photos', 0),
(NULL, '_aqb_points_action_bx_photos_delete', '', 'delete', 'bx_photos', -1, 100, 'true', 'photos', 'delete_media', 'photos', 1),
(NULL, '_aqb_points_action_bx_poll_answered_recipient', '', 'answered', 'bx_poll', 2, 100, 'true', 'poll', 'cookie', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_delete_poll', '', 'delete_poll', 'bx_poll', -1, 100, 'true', 'poll', 'cookie', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_add', '', 'add', 'bx_poll', 1, 100, 'true', 'poll', 'cookie', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_edit', '', 'edit', 'bx_poll', 1, 100, 'true', 'poll', 'cookie', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_answered', '', 'answered', 'bx_poll', 1, 100, 'true', 'poll', 'first', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_commentPost', '', 'commentPost', 'bx_poll', 1, 100, 'true', 'poll', 'second', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_commentRated', '', 'commentRated', 'bx_poll', 1, 100, 'true', 'poll', 'second', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_commentRemoved', '', 'commentRemoved', 'bx_poll', -1, 100, 'true', 'poll', 'second', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_commentUpdated', '', 'commentUpdated', 'bx_poll', 1, 100, 'true', 'poll', 'second', 'poll', 0),
(NULL, '_aqb_points_action_bx_poll_rate', '', 'rate', 'bx_poll', 1, 100, 'true', 'poll', 'second', 'poll', 0),
(NULL, '_aqb_points_action_bx_sites_add', '', 'add', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_change', '', 'change', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_delete', '', 'delete', 'bx_sites', -1, 100, 'true', 'sites', 'second', 'sites', 1),
(NULL, '_aqb_points_action_bx_sites_mark_as_featured', '', 'mark_as_featured', 'bx_sites', 1, 100, 'true', 'sites', 'cookie', 'sites', 1),
(NULL, '_aqb_points_action_bx_sites_rate', '', 'rate', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_commentPost', '', 'commentPost', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_commentRemoved', '', 'commentRemoved', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_commentUpdated', '', 'commentUpdated', 'bx_sites', 1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sites_commentRated', '', 'commentRated', 'bx_sites', -1, 100, 'true', 'sites', 'second', 'sites', 0),
(NULL, '_aqb_points_action_bx_sounds_add', '', 'add', 'bx_sounds', 1, 100, 'true', 'sounds', 'second', 'sounds', 1),
(NULL, '_aqb_points_action_bx_sounds_commentPost', '', 'commentPost', 'bx_sounds', 1, 100, 'true', 'sounds', 'second', 'sounds', 0),
(NULL, '_aqb_points_action_bx_sounds_commentRated', '', 'commentRated', 'bx_sounds', -1, 100, 'true', 'sounds', 'second', 'sounds', 0),
(NULL, '_aqb_points_action_bx_sounds_commentRemoved', '', 'commentRemoved', 'bx_sounds', 1, 100, 'true', 'sounds', 'second', 'sounds', 0),
(NULL, '_aqb_points_action_bx_sounds_commentUpdated', '', 'commentUpdated', 'bx_sounds', 1, 100, 'true', 'sounds', 'second', 'sounds', 0),
(NULL, '_aqb_points_action_bx_sounds_rate', '', 'rate', 'bx_sounds', 1, 100, 'true', 'sounds', 'second', 'sounds', 0),
(NULL, '_aqb_points_action_bx_sounds_delete', '', 'delete', 'bx_sounds', -1, 100, 'true', 'sounds', 'delete_media', 'sounds', 1),
(NULL, '_aqb_points_action_bx_store_rate', '', 'rate', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_add', '', 'add', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_change', '', 'change', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_delete', '', 'delete', 'bx_store', -1, 100, 'true', 'store', 'second', 'store', 1),
(NULL, '_aqb_points_action_bx_store_mark_as_featured', '', 'mark_as_featured', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 1),
(NULL, '_aqb_points_action_bx_store_commentPost', '', 'commentPost', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_commentRated', '', 'commentRated', 'bx_store', -1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_commentRemoved', '', 'commentRemoved', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_store_commentUpdated', '', 'commentUpdated', 'bx_store', 1, 100, 'true', 'store', 'second', 'store', 0),
(NULL, '_aqb_points_action_bx_videos_add', '', 'add', 'bx_videos', 1, 100, 'true', 'videos', 'second', 'videos', 1),
(NULL, '_aqb_points_action_bx_videos_commentPost', '', 'commentPost', 'bx_videos', 1, 100, 'true', 'videos', 'second', 'videos', 0),
(NULL, '_aqb_points_action_bx_videos_commentRated', '', 'commentRated', 'bx_videos', -1, 100, 'true', 'videos', 'second', 'videos', 0),
(NULL, '_aqb_points_action_bx_videos_commentRemoved', '', 'commentRemoved', 'bx_videos', 1, 100, 'true', 'videos', 'second', 'videos', 0),
(NULL, '_aqb_points_action_bx_videos_commentUpdated', '', 'commentUpdated', 'bx_videos', 1, 100, 'true', 'videos', 'second', 'videos', 0),
(NULL, '_aqb_points_action_bx_videos_rate', '', 'rate', 'bx_videos', 1, 100, 'true', 'videos', 'second', 'videos', 0),
(NULL, '_aqb_points_action_bx_videos_delete', '', 'delete', 'bx_videos', -1, 100, 'true', 'videos', 'delete_media', 'videos', 1),
(NULL, '_aqb_points_action_bx_wall_commentPost', '', 'commentPost', 'bx_wall', 1, 100, 'true', 'wall', 'second', 'wall', 0),
(NULL, '_aqb_points_action_bx_wall_commentRated', '', 'commentRated', 'bx_wall', -1, 100, 'true', 'wall', 'second', 'wall', 0),
(NULL, '_aqb_points_action_bx_wall_commentRemoved', '', 'commentRemoved', 'bx_wall', 1, 100, 'true', 'wall', 'second', 'wall', 0),
(NULL, '_aqb_points_action_bx_wall_commentUpdated', '', 'commentUpdated', 'bx_wall', 1, 100, 'true', 'wall', 'second', 'wall', 0),
(NULL, '_aqb_points_action_for_your_profile_commentPost', '', 'commentPost', 'profile', 1, 100, 'true', '', 'cmts', 'profile', 0),
(NULL, '_aqb_points_action_for_your_ads_commentPost', '', 'commentPost', 'ads', 1, 100, 'true', 'ads', 'cmts', 'ads', 0),
(NULL, '_aqb_points_action_for_your_bx_articles_commentPost', '', 'commentPost', 'bx_articles', 1, 100, 'true', 'articles', 'cmts', 'articles', 0),
(NULL, '_aqb_points_action_for_your_bx_blogs_commentPost', '', 'commentPost', 'blogposts', 1, 100, 'true', 'blogs', 'cmts', 'blogs', 0),
(NULL, '_aqb_points_action_for_your_bx_events_commentPost', '', 'commentPost', 'bx_events', 1, 100, 'true', 'events', 'cmts', 'events', 0),
(NULL, '_aqb_points_action_for_your_bx_feedback_commentPost', '', 'commentPost', 'bx_feedback', 1, 100, 'true', 'feedback', 'cmts', 'feedback', 0),
(NULL, '_aqb_points_action_for_your_bx_files_commentPost', '', 'commentPost', 'bx_files', 1, 100, 'true', 'files', 'cmts', 'files', 0),
(NULL, '_aqb_points_action_for_your_bx_groups_commentPost', '', 'commentPost', 'bx_groups', 1, 100, 'true', 'groups', 'cmts', 'groups', 0),
(NULL, '_aqb_points_action_for_your_news_commentPost', '', 'commentPost', 'bx_news', 1, 100, 'true', 'news', 'cmts', 'news', 0),
(NULL, '_aqb_points_action_for_your_bx_photos_commentPost', '', 'commentPost', 'bx_photos', 1, 100, 'true', 'photos', 'cmts', 'photos', 0),
(NULL, '_aqb_points_action_for_your_bx_poll_commentPost', '', 'commentPost', 'bx_poll', 1, 100, 'true', 'poll', 'cmts', 'poll', 0),
(NULL, '_aqb_points_action_for_your_bx_sites_commentPost', '', 'commentPost', 'bx_sites', 1, 100, 'true', 'sites', 'cmts', 'sites', 0),
(NULL, '_aqb_points_action_for_your_bx_sounds_commentPost', '', 'commentPost', 'bx_sounds', 1, 100, 'true', 'sounds', 'cmts', 'sounds', 0),
(NULL, '_aqb_points_action_for_your_bx_store_commentPost', '', 'commentPost', 'bx_store', 1, 100, 'true', 'store', 'cmts', 'store', 0),
(NULL, '_aqb_points_action_for_your_bx_videos_commentPost', '', 'commentPost', 'bx_videos', 1, 100, 'true', 'videos', 'cmts', 'videos', 0),
(NULL, '_aqb_points_action_for_your_bx_wall_commentPost', '', 'commentPost', 'bx_wall', 1, 100, 'true', 'wall', 'cmts', 'wall', 0),
(NULL, '_aqb_points_action_for_your_profile_rate', '', 'rate', 'profile', 2, 100, 'true', '', 'vote', 'profile', 0),
(NULL, '_aqb_points_action_for_your_ads_rate', '', 'rate', 'ads', 1, 100, 'true', 'ads', 'vote', 'ads', 0),
(NULL, '_aqb_points_action_for_your_bx_articles_rate', '', 'rate', 'bx_articles', 1, 100, 'true', 'articles', 'vote', 'articles', 0),
(NULL, '_aqb_points_action_for_your_bx_blogs_rate', '', 'rate', 'blogposts', 1, 100, 'true', 'blogs', 'vote', 'blogs', 0),
(NULL, '_aqb_points_action_for_your_bx_events_rate', '', 'rate', 'bx_events', 1, 100, 'true', 'events', 'vote', 'events', 0),
(NULL, '_aqb_points_action_for_your_bx_feedback_rate', '', 'rate', 'bx_feedback', 2, 100, 'true', 'feedback', 'vote', 'feedback', 0),
(NULL, '_aqb_points_action_for_your_bx_files_rate', '', 'rate', 'bx_files', 1, 100, 'true', 'files', 'vote', 'files', 0),
(NULL, '_aqb_points_action_for_your_bx_groups_rate', '', 'rate', 'bx_groups', 1, 100, 'true', 'groups', 'vote', 'groups', 0),
(NULL, '_aqb_points_action_for_your_bx_news_rate', '', 'rate', 'bx_news', 2, 100, 'true', 'news', 'vote', 'news', 0),
(NULL, '_aqb_points_action_for_your_bx_photos_rate', '', 'rate', 'bx_photos', 1, 100, 'true', 'photos', 'vote', 'photos', 0),
(NULL, '_aqb_points_action_for_your_bx_poll_rate', '', 'rate', 'bx_poll', 1, 100, 'true', 'poll', 'vote', 'poll', 0),
(NULL, '_aqb_points_action_for_your_bx_sites_rate', '', 'rate', 'bx_sites', 1, 100, 'true', 'sites', 'vote', 'sites', 0),
(NULL, '_aqb_points_action_for_your_bx_sounds_rate', '', 'rate', 'bx_sounds', 1, 100, 'true', 'sounds', 'vote', 'sounds', 0),
(NULL, '_aqb_points_action_for_your_bx_store_rate', '', 'rate', 'bx_store', 1, 100, 'true', 'store', 'vote', 'store', 0),
(NULL, '_aqb_points_action_for_your_bx_videos_rate', '', 'rate', 'bx_videos', 1, 100, 'true', 'videos', 'vote', 'videos', 0),
(NULL, '_aqb_points_action_for_your_profile_commentRated', '', 'commentRated', 'profile', 1, 100, 'true', '', 'cmts_rate', 'profile', 0),
(NULL, '_aqb_points_action_for_your_ads_commentRated', '', 'commentRated', 'ads', 1, 100, 'true', 'ads', 'cmts_rate', 'ads', 0),
(NULL, '_aqb_points_action_for_your_bx_articles_commentRated', '', 'commentRated', 'bx_articles', 1, 100, 'true', 'articles', 'cmts_rate', 'articles', 0),
(NULL, '_aqb_points_action_for_your_bx_blogs_commentRated', '', 'commentRated', 'blogposts', 1, 100, 'true', 'blogs', 'cmts_rate', 'blogs', 0),
(NULL, '_aqb_points_action_for_your_bx_events_commentRated', '', 'commentRated', 'bx_events', 1, 100, 'true', 'events', 'cmts_rate', 'events', 0),
(NULL, '_aqb_points_action_for_your_bx_feedback_commentRated', '', 'commentRated', 'bx_feedback', 1, 100, 'true', 'feedback', 'cmts_rate', 'feedback', 0),
(NULL, '_aqb_points_action_for_your_bx_files_commentRated', '', 'commentRated', 'bx_files', 1, 100, 'true', 'files', 'cmts_rate', 'files', 0),
(NULL, '_aqb_points_action_for_your_bx_groups_commentRated', '', 'commentRated', 'bx_groups', 1, 100, 'true', 'groups', 'cmts_rate', 'groups', 0),
(NULL, '_aqb_points_action_for_your_news_commentRated', '', 'commentRated', 'bx_news', 1, 100, 'true', 'news', 'cmts_rate', 'news', 0),
(NULL, '_aqb_points_action_for_your_bx_photos_commentRated', '', 'commentRated', 'bx_photos', 1, 100, 'true', 'photos', 'cmts_rate', 'photos', 0),
(NULL, '_aqb_points_action_for_your_bx_poll_commentRated', '', 'commentRated', 'bx_poll', 1, 100, 'true', 'poll', 'cmts_rate', 'poll', 0),
(NULL, '_aqb_points_action_for_your_bx_sites_commentRated', '', 'commentRated', 'bx_sites', -1, 100, 'true', 'sites', 'cmts_rate', 'sites', 0),
(NULL, '_aqb_points_action_for_your_bx_sounds_commentRated', '', 'commentRated', 'bx_sounds', -1, 100, 'true', 'sounds', 'cmts_rate', 'sounds', 0),
(NULL, '_aqb_points_action_for_your_bx_store_commentRated', '', 'commentRated', 'bx_store', -1, 100, 'true', 'store', 'cmts_rate', 'store', 0),
(NULL, '_aqb_points_action_for_your_bx_videos_commentRated', '', 'commentRated', 'bx_videos', -1, 100, 'true', 'videos', 'cmts_rate', 'videos', 0),
(NULL, '_aqb_points_action_for_your_bx_wall_commentRated', '', 'commentRated', 'bx_wall', -1, 100, 'true', 'wall', 'cmts_rate', 'wall', 0),
(NULL, '_aqb_points_action_for_your_profile_commentRated_negative', '', 'commentRated', 'profile', -1, 100, 'true', '', 'cmts_rate_negative', 'profile', 0),
(NULL, '_aqb_points_action_for_your_ads_commentRated_negative', '', 'commentRated', 'ads', -1, 100, 'true', 'ads', 'cmts_rate_negative', 'ads', 0),
(NULL, '_aqb_points_action_for_your_bx_articles_commentRated_negative', '', 'commentRated', 'bx_articles', -1, 100, 'true', 'articles', 'cmts_rate_negative', 'articles', 0),
(NULL, '_aqb_points_action_for_your_bx_blogs_commentRated_negative', '', 'commentRated', 'blogposts', -1, 100, 'true', 'blogs', 'cmts_rate_negative', 'blogs', 0),
(NULL, '_aqb_points_action_for_your_bx_events_commentRated_negative', '', 'commentRated', 'bx_events', -1, 100, 'true', 'events', 'cmts_rate_negative', 'events', 0),
(NULL, '_aqb_points_action_for_your_bx_feedback_commentRated_negative', '', 'commentRated', 'bx_feedback', -1, 100, 'true', 'feedback', 'cmts_rate_negative', 'feedback', 0),
(NULL, '_aqb_points_action_for_your_bx_files_commentRated_negative', '', 'commentRated', 'bx_files', -1, 100, 'true', 'files', 'cmts_rate_negative', 'files', 0),
(NULL, '_aqb_points_action_for_your_bx_groups_commentRated_negative', '', 'commentRated', 'bx_groups', -1, 100, 'true', 'groups', 'cmts_rate_negative', 'groups', 0),
(NULL, '_aqb_points_action_for_your_news_commentRated_negative', '', 'commentRated', 'bx_news', -1, 100, 'true', 'news', 'cmts_rate_negative', 'news', 0),
(NULL, '_aqb_points_action_for_your_bx_photos_commentRated_negative', '', 'commentRated', 'bx_photos', -1, 100, 'true', 'photos', 'cmts_rate_negative', 'photos', 0),
(NULL, '_aqb_points_action_for_your_bx_poll_commentRated_negative', '', 'commentRated', 'bx_poll', -1, 100, 'true', 'poll', 'cmts_rate_negative', 'poll', 0),
(NULL, '_aqb_points_action_for_your_bx_sites_commentRated_negative', '', 'commentRated', 'bx_sites', -1, 100, 'true', 'sites', 'cmts_rate_negative', 'sites', 0),
(NULL, '_aqb_points_action_for_your_bx_sounds_commentRated_negative', '', 'commentRated', 'bx_sounds', -1, 100, 'true', 'sounds', 'cmts_rate_negative', 'sounds', 0),
(NULL, '_aqb_points_action_for_your_bx_store_commentRated_negative', '', 'commentRated', 'bx_store', -1, 100, 'true', 'store', 'cmts_rate_negative', 'store', 0),
(NULL, '_aqb_points_action_for_your_bx_videos_commentRated_negative', '', 'commentRated', 'bx_videos', -1, 100, 'true', 'videos', 'cmts_rate_negative', 'videos', 0),
(NULL, '_aqb_points_action_for_your_bx_wall_commentRated_negative', '', 'commentRated', 'bx_wall', -1, 100, 'true', 'wall', 'cmts_rate_negative', 'wall', 0),
(NULL, '_aqb_points_action_for_your_bx_forum_vote', '', 'vote', 'bx_forum', 1, 100, 'true', 'forum', 'topic_owner', 'forum', 0),
(NULL, '_aqb_points_action_profile_membership_upgraded', '', 'set_membership', 'profile', 1, 100, 'true', '', 'second', 'profile', 0);


CREATE TABLE IF NOT EXISTS `[db_prefix]modules` (
  `module_uri` varchar(32) NOT NULL default '',  
  `hasactions` enum('true','false') NOT NULL default 'true',
   UNIQUE KEY (`module_uri`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;


INSERT INTO `[db_prefix]modules` VALUES 
('ads', 'true'),
('articles', 'true'),
('avatar', 'true'),
('blogs', 'true'),
('board', 'false'),
('chat', 'false'),
('custom_rss', 'false'),
('data_migration', 'false'),
('desktop', 'false'),
('events', 'true'),
('facebook_connect', 'false'),
('feedback', 'true'),
('files', 'true'),
('google_search', 'false'),
('map_profiles', 'false'),
('membership', 'false'),
('messenger', 'false'),
('news', 'true'),
('payment', 'false'),
('photos', 'true'),
('poll', 'true'),
('profiler', 'false'),
('profile_customize', 'false'),
('quotes', 'false'),
('shoutbox', 'false'),
('simple_messenger', 'false'),
('sites', 'true'),
('sounds', 'true'),
('spy', 'false'),
('videos', 'true'),
('wall', 'true'),
('store', 'true'),
('open_social', 'false'),
('groups', 'true'),
('forum', 'true');

INSERT INTO `sys_alerts_handlers` VALUES (NULL, 'aqb_points_assign_alert', 'AqbPointsAlertsResponse', 'modules/aqb/points/classes/AqbPointsAlertsResponse.php', '');
SET @iHandler := LAST_INSERT_ID();
INSERT INTO `sys_alerts` VALUES
(NULL, 'profile', 'join', @iHandler),
(NULL, 'profile', 'delete', @iHandler),
(NULL, 'profile', 'login', @iHandler),
(NULL, 'profile', 'logout', @iHandler),
(NULL, 'profile', 'edit', @iHandler),
(NULL, 'profile', 'change_status', @iHandler),
(NULL, 'profile', 'send_mail_internal', @iHandler),
(NULL, 'profile', 'commentPost', @iHandler),
(NULL, 'profile', 'commentRated', @iHandler),
(NULL, 'profile', 'commentRemoved', @iHandler),
(NULL, 'profile', 'commentUpdated', @iHandler),
(NULL, 'profile', 'edit_status', @iHandler),
(NULL, 'profile', 'edit_status_message', @iHandler),
(NULL, 'friend', 'delete', @iHandler),
(NULL, 'friend', 'accept', @iHandler),
(NULL, 'friend', 'request', @iHandler),
(NULL, 'ads', 'edit', @iHandler),
(NULL, 'ads', 'create', @iHandler),
(NULL, 'ads', 'delete', @iHandler),
(NULL, 'ads', 'buy', @iHandler),
(NULL, 'ads', 'view', @iHandler),
(NULL, 'ads', 'rate', @iHandler),
(NULL, 'ads', 'commentPost', @iHandler),
(NULL, 'ads', 'commentRated', @iHandler),
(NULL, 'ads', 'commentRemoved', @iHandler),
(NULL, 'ads', 'commentUpdated', @iHandler),
(NULL, 'bx_articles', 'featured', @iHandler),
(NULL, 'bx_articles', 'delete', @iHandler),
(NULL, 'bx_articles', 'publish', @iHandler),
(NULL, 'bx_articles', 'unpublish', @iHandler),
(NULL, 'bx_articles', 'commentPost', @iHandler),
(NULL, 'bx_articles', 'commentRated', @iHandler),
(NULL, 'bx_articles', 'commentRemoved', @iHandler),
(NULL, 'bx_articles', 'commentUpdated', @iHandler),
(NULL, 'articles', 'post', @iHandler),
(NULL, 'articles', 'edit', @iHandler),
(NULL, 'bx_avatar', 'add', @iHandler),
(NULL, 'bx_avatar', 'change', @iHandler),
(NULL, 'bx_blogs', 'view_post', @iHandler),
(NULL, 'bx_blogs', 'create', @iHandler),
(NULL, 'bx_blogs', 'edit_post', @iHandler),
(NULL, 'bx_blogs', 'delete_post', @iHandler),
(NULL, 'blogposts', 'commentPost', @iHandler),
(NULL, 'blogposts', 'commentRated', @iHandler),
(NULL, 'blogposts', 'commentRemoved', @iHandler),
(NULL, 'blogposts', 'commentUpdated', @iHandler),
(NULL, 'bx_events', 'join', @iHandler),
(NULL, 'bx_events', 'add', @iHandler),
(NULL, 'bx_events', 'join_request', @iHandler),
(NULL, 'bx_events', 'join_reject', @iHandler),
(NULL, 'bx_events', 'join_confirm', @iHandler),
(NULL, 'bx_events', 'change', @iHandler),
(NULL, 'bx_events', 'delete', @iHandler),
(NULL, 'bx_events', 'fan_remove', @iHandler),
(NULL, 'bx_events', 'fan_become_admin', @iHandler),
(NULL, 'bx_events', 'admin_become_fan', @iHandler),
(NULL, 'bx_events', 'mark_as_featured', @iHandler),
(NULL, 'bx_events', 'commentPost', @iHandler),
(NULL, 'bx_events', 'commentRated', @iHandler),
(NULL, 'bx_events', 'commentRemoved', @iHandler),
(NULL, 'bx_events', 'commentUpdated', @iHandler),
(NULL, 'feedback', 'post', @iHandler),
(NULL, 'feedback', 'edit', @iHandler),
(NULL, 'bx_feedback', 'approve', @iHandler),
(NULL, 'bx_feedback', 'reject', @iHandler),
(NULL, 'bx_feedback', 'delete', @iHandler),
(NULL, 'bx_feedback', 'commentPost', @iHandler),
(NULL, 'bx_feedback', 'commentRated', @iHandler),
(NULL, 'bx_feedback', 'commentRemoved', @iHandler),
(NULL, 'bx_feedback', 'commentUpdated', @iHandler),
(NULL, 'bx_files', 'add', @iHandler),
(NULL, 'bx_files', 'commentPost', @iHandler),
(NULL, 'bx_files', 'commentRated', @iHandler),
(NULL, 'bx_files', 'commentRemoved', @iHandler),
(NULL, 'bx_files', 'commentUpdated', @iHandler),
(NULL, 'bx_files', 'rate', @iHandler),
(NULL, 'bx_files', 'delete', @iHandler),
(NULL, 'bx_forum', 'reply', @iHandler),
(NULL, 'bx_forum', 'post_edit', @iHandler),
(NULL, 'bx_forum', 'edit_del', @iHandler),
(NULL, 'bx_forum', 'new_topic', @iHandler),
(NULL, 'bx_forum', 'vote', @iHandler),
(NULL, 'bx_forum', 'post_report', @iHandler),
(NULL, 'bx_forum', 'flag', @iHandler),
(NULL, 'bx_forum', 'unflag', @iHandler),
(NULL, 'bx_groups', 'join', @iHandler),
(NULL, 'bx_groups', 'join_request', @iHandler),
(NULL, 'bx_groups', 'join_reject', @iHandler),
(NULL, 'bx_groups', 'join_confirm', @iHandler),
(NULL, 'bx_groups', 'add', @iHandler),
(NULL, 'bx_groups', 'change', @iHandler),
(NULL, 'bx_groups', 'delete', @iHandler),
(NULL, 'bx_groups', 'fan_remove', @iHandler),
(NULL, 'bx_groups', 'fan_become_admin', @iHandler),
(NULL, 'bx_groups', 'admin_become_fan', @iHandler),
(NULL, 'bx_groups', 'mark_as_featured', @iHandler),
(NULL, 'bx_groups', 'commentPost', @iHandler),
(NULL, 'bx_groups', 'commentRated', @iHandler),
(NULL, 'bx_groups', 'commentRemoved', @iHandler),
(NULL, 'bx_groups', 'commentUpdated', @iHandler),
(NULL, 'bx_map', 'geolocate_profile', @iHandler),
(NULL, 'bx_map', 'geolocate_city', @iHandler),
(NULL, 'bx_map', 'geolocate_country', @iHandler),
(NULL, 'bx_map', 'location_manually_updated', @iHandler),
(NULL, 'bx_news', 'post', @iHandler),
(NULL, 'bx_news', 'edit', @iHandler),
(NULL, 'bx_news', 'featured', @iHandler),
(NULL, 'bx_news', 'publish', @iHandler),
(NULL, 'bx_news', 'unpublish', @iHandler),
(NULL, 'bx_news', 'delete', @iHandler),
(NULL, 'bx_news', 'commentPost', @iHandler),
(NULL, 'bx_news', 'commentRemoved', @iHandler),
(NULL, 'bx_news', 'commentUpdated', @iHandler),
(NULL, 'bx_news', 'commentRated', @iHandler),
(NULL, 'bx_photos', 'add', @iHandler),
(NULL, 'bx_photos', 'commentPost', @iHandler),
(NULL, 'bx_photos', 'commentRemoved', @iHandler),
(NULL, 'bx_photos', 'commentUpdated', @iHandler),
(NULL, 'bx_photos', 'commentRated', @iHandler),
(NULL, 'bx_photos', 'rate', @iHandler),
(NULL, 'bx_photos', 'delete', @iHandler),
(NULL, 'bx_sites', 'add', @iHandler),
(NULL, 'bx_sites', 'change', @iHandler),
(NULL, 'bx_sites', 'delete', @iHandler),
(NULL, 'bx_sites', 'mark_as_featured', @iHandler),
(NULL, 'bx_sites', 'rate', @iHandler),
(NULL, 'bx_sites', 'commentPost', @iHandler),
(NULL, 'bx_sites', 'commentRemoved', @iHandler),
(NULL, 'bx_sites', 'commentUpdated', @iHandler),
(NULL, 'bx_sites', 'commentRated', @iHandler),
(NULL, 'bx_sounds', 'add', @iHandler),
(NULL, 'bx_sounds', 'commentPost', @iHandler),
(NULL, 'bx_sounds', 'commentRated', @iHandler),
(NULL, 'bx_sounds', 'commentRemoved', @iHandler),
(NULL, 'bx_sounds', 'commentUpdated', @iHandler),
(NULL, 'bx_sounds', 'rate', @iHandler),
(NULL, 'bx_sounds', 'delete', @iHandler),
(NULL, 'bx_store', 'add', @iHandler),
(NULL, 'bx_store', 'change', @iHandler),
(NULL, 'bx_store', 'delete', @iHandler),
(NULL, 'bx_store', 'mark_as_featured', @iHandler),
(NULL, 'bx_store', 'commentPost', @iHandler),
(NULL, 'bx_store', 'commentRated', @iHandler),
(NULL, 'bx_store', 'commentRemoved', @iHandler),
(NULL, 'bx_store', 'commentUpdated', @iHandler),
(NULL, 'bx_videos', 'add', @iHandler),
(NULL, 'bx_videos', 'commentPost', @iHandler),
(NULL, 'bx_videos', 'commentRated', @iHandler),
(NULL, 'bx_videos', 'commentRemoved', @iHandler),
(NULL, 'bx_videos', 'commentUpdated', @iHandler),
(NULL, 'bx_videos', 'rate', @iHandler),
(NULL, 'bx_videos', 'delete', @iHandler),
(NULL, 'bx_wall', 'commentPost', @iHandler),
(NULL, 'bx_wall', 'commentRated', @iHandler),
(NULL, 'bx_wall', 'commentRemoved', @iHandler),
(NULL, 'bx_wall', 'commentUpdated', @iHandler),
(NULL, 'fave', 'delete', @iHandler),
(NULL, 'fave', 'add', @iHandler),
(NULL, 'block', 'delete', @iHandler),
(NULL, 'block', 'add', @iHandler),
(NULL, 'bx_articles', 'rate', @iHandler),
(NULL, 'blogposts', 'rate', @iHandler),
(NULL, 'bx_events', 'rate', @iHandler),
(NULL, 'bx_feedback', 'rate', @iHandler),
(NULL, 'bx_groups', 'rate', @iHandler),
(NULL, 'bx_news', 'rate', @iHandler),
(NULL, 'bx_poll', 'vote', @iHandler),
(NULL, 'bx_poll', 'delete_poll', @iHandler),
(NULL, 'bx_poll', 'add', @iHandler),
(NULL, 'bx_poll', 'edit', @iHandler),
(NULL, 'bx_poll', 'answered', @iHandler),
(NULL, 'bx_poll', 'commentPost', @iHandler),
(NULL, 'bx_poll', 'commentRated', @iHandler),
(NULL, 'bx_poll', 'commentRemoved', @iHandler),
(NULL, 'bx_poll', 'commentUpdated', @iHandler),
(NULL, 'bx_poll', 'rate', @iHandler),
(NULL, 'bx_store', 'rate', @iHandler),
(NULL, 'profile', 'rate', @iHandler),
(NULL, 'aqb_points', 'assign', @iHandler),
(NULL, 'profile', 'set_membership', @iHandler);

INSERT INTO `sys_menu_top` (`Parent`, `Name`, `Caption`, `Link`, `Order`, `Visible`, `Target`, `Onclick`, `Check`, `Editable`, `Deletable`, `Active`, `Type`, `Picture`, `BQuickLink`, `Statistics`) VALUES
(118, 'My Points', '_aqb_my_points_link_title', 'modules/?r=aqb_points/history', 12, 'memb', '', '', '', 1, 1, 1, 'custom', '', 0, ''),
(6, 'Points Leaders', '_aqb_browse_points_leaders', 'modules/?r=aqb_points/leaders', 12, 'memb', '', '', '', 1, 1, 1, 'custom', '', 0, '');

SET @iTopMenuLastOrder := (SELECT `Order` + 1 FROM `sys_menu_top` WHERE `Parent` = 0 ORDER BY `Order` DESC LIMIT 1);
INSERT INTO `sys_menu_top` (`ID`, `Parent`, `Name`, `Caption`, `Link`, `Order`, `Visible`, `Target`, `Onclick`, `Check`, `Editable`, `Deletable`, `Active`, `Type`, `Picture`, `BQuickLink`, `Statistics`) 
VALUES(NULL, 0, @sPluginName, '_aqb_points_mem_points', 'modules/?r=aqb_points/membership', @iTopMenuLastOrder, 'memb', '', '', '', 1, 1, 1, 'top', 'modules/aqb/points/|points_mem_menu_icon.png', 1, '');

SET @iOrder = (SELECT MAX(`Order`) FROM `sys_page_compose_pages`) + 1;
INSERT INTO `sys_page_compose_pages`(`Name`, `Title`, `Order`) VALUES ('aqb_points_membership', 'Points to Membership', @iOrder);

INSERT INTO `sys_page_compose` (`Page`, `PageWidth`, `Desc`, `Caption`, `Column`, `Order`, `Func`, `Content`, `DesignBox`, `ColWidth`, `Visible`, `MinWidth`) VALUES
('aqb_points_membership', '998px', 'My Level', '_aqb_points_my_membership_status', 1, 0, 'My', '', 1, 30, 'memb', 0),
('aqb_points_membership', '998px', 'Available Levels', '_aqb_points_avail_levels', 2, 0, 'AllAvailable', '', 1, 70, 'memb', 0);

INSERT INTO `sys_page_compose` (`ID`, `Page`, `PageWidth`, `Desc`, `Caption`, `Column`, `Order`, `Func`, `Content`, `DesignBox`, `ColWidth`, `Visible`, `MinWidth`) VALUES
(NULL, 'index', '998px', @sPluginTitle, '_aqb_browse_points_leaders', 1, 2, 'PHP', 'return BxDolService::call(''aqb_points'', ''points_leaders_index_page'');', 1, 66, 'non,memb', 0);

INSERT INTO `sys_objects_actions` (`Caption`, `Icon`, `Url`, `Script`, `Eval`, `Order`, `Type`, `bDisplayInSubMenuHeader`) VALUES
('{evalResult}', 'modules/aqb/points/|points_action.png', '', '$(''#login_div'').remove(); showPopupAnyHtml (''modules/?r=aqb_points/get_present_points_form/{ID}'');', 'if (($GLOBALS[''logged''][''member''] || $GLOBALS[''logged''][''admin'']) && {ID} != {member_id} && getParam(''aqb_points_enable_present_points'') == ''on'') return _t(''_aqb_points_present_link'');', 10, 'Profile', 0);

INSERT INTO `sys_cron_jobs` (`name`, `time`, `class`, `file`, `eval`) VALUES
('aqb_points_reports', '0 0 * * *', 'AqbPointsCron', 'modules/aqb/points/classes/AqbPointsCron.php', '');

ALTER TABLE `Profiles` ADD `AqbPoints` int(10) unsigned NOT NULL default '0';
ALTER TABLE `Profiles` ADD `AqbPointsLevel` tinyint(1) unsigned NOT NULL default '0';

INSERT INTO `sys_profile_fields` (`ID`, `Name`, `Type`, `Control`, `Extra`, `Min`, `Max`, `Values`, `UseLKey`, `Check`, `Unique`, `Default`, `Mandatory`, `Deletable`, `JoinPage`, `JoinBlock`, `JoinOrder`, `EditOwnBlock`, `EditOwnOrder`, `EditAdmBlock`, `EditAdmOrder`, `EditModBlock`, `EditModOrder`, `ViewMembBlock`, `ViewMembOrder`, `ViewAdmBlock`, `ViewAdmOrder`, `ViewModBlock`, `ViewModOrder`, `ViewVisBlock`, `ViewVisOrder`, `SearchParams`, `SearchSimpleBlock`, `SearchSimpleOrder`, `SearchQuickBlock`, `SearchQuickOrder`, `SearchAdvBlock`, `SearchAdvOrder`, `MatchField`, `MatchPercent`) 
VALUES (NULL, 'AqbPoints', 'num', NULL, '', NULL, NULL, '', 'LKey', '', 0, '0', 0, 1, 0, 0, NULL, 0, NULL, 0, NULL, 0, NULL, 17, 1, 17, 2, 0, NULL, 17, 1, '', 0, NULL, 0, NULL, 0, NULL, 0, 0);

INSERT INTO `sys_page_compose` (`ID`, `Page`, `PageWidth`, `Desc`, `Caption`, `Column`, `Order`, `Func`, `Content`, `DesignBox`, `ColWidth`, `Visible`, `MinWidth`) VALUES
(NULL, 'member', '998px', 'Levels info block', '_aqb_points_levels_info', 1, 0, 'PHP', 'return BxDolService::call(''aqb_points'', ''levels_account_page_block'');', 1, 34, 'memb', 0);

INSERT INTO `sys_page_compose` (`ID`, `Page`, `PageWidth`, `Desc`, `Caption`, `Column`, `Order`, `Func`, `Content`, `DesignBox`, `ColWidth`, `Visible`, `MinWidth`) VALUES
(NULL, 'profile', '998px', 'Profile''s levels info block', '_aqb_points_levels_info_profile', 1, 0, 'PHP', 'return BxDolService::call(''aqb_points'', ''levels_profile_page_block'', array($this->oProfileGen->_iProfileID));', 1, 34, 'non,memb', 0);
