<?
/**********************************************************************************
*                            IBDW MobileWall Dolphin Smart Community Builder
*                              -------------------
*     begin                : Oct 18 2011
*     copyright            : (C) 2011 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW MobileWall is not free and you cannot redistribute and/or modify it.
* 
* IBDW MobileWall is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'mobilewall';
$aLangContent = array(
'_ibdw_mobilewall_member_subscribed' => 'joined',
'_ibdw_mobilewall_spyprofile' => 'viewed the profile of {recipient_p_nick}',
'_ibdw_mobilewall_profile_edit' => 'changed own profile',
'_ibdw_mobilewall_profile_rate' => 'rated the profile {recipient_p_nick}',
'_ibdw_mobilewall_isfriend' => 'is now friends with {recipient_p_nick}',
'_ibdw_mobilewall_site_edit' => 'changed the site {site_caption}',
'_ibdw_mobilewall_site_rate' => 'rated the site {site_caption}',
'_ibdw_mobilewall_site_comment' => 'commented the site {site_caption}',	
'_ibdw_mobilewall_comment_nphoto' => 'commented the photo of {recipient_p_nick}',
'_ibdw_mobilewall_comment_name' => 'commented the video of {recipient_p_nick}',
'_ibdw_mobilewall_rated_videos' => 'rated the video of {recipient_p_nick}',
'_ibdw_mobilewall_reply_polls' => 'replied the poll of {recipient_p_nick}',
'_ibdw_mobilewall_rated_polls' => 'rated the poll of {recipient_p_nick}',
'_ibdw_mobilewall_comment_polls' => 'commented the poll of {recipient_p_nick}',
'_ibdw_mobilewall_rate_photo' => 'rated the photo of {recipient_p_nick}',
'_ibdw_mobilewall_ads_rate' => 'rated the ad {ads_caption}',
'_ibdw_mobilewall_ads_add' => 'added a new ad {ads_caption}',
'_ibdw_mobilewall_photo_add' => 'added a new photo {photo_caption}',
'_ibdw_mobilewall_video_add' => 'added a new video {video_caption}',
'_ibdw_mobilewall_site_add' => 'added a new site {site_caption}',
'_ibdw_mobilewall_group_add' => 'created the group {group_caption}',
'_ibdw_mobilewall_group_editaw' => 'changed the group {group_caption}',
'_ibdw_mobilewall_group_join' => 'joined the group {group_caption}',
'_ibdw_mobilewall_group_rate' => 'rated the group {group_caption}', 
'_ibdw_mobilewall_group_comment' => 'commented on the group {group_caption}',
'_ibdw_mobilewall_event_add' => 'added a new event {event_caption}',
'_ibdw_mobilewall_event_join' => 'joined at the event {event_caption}',
'_ibdw_mobilewall_event_rate' => 'rated the event {event_caption}',
'_ibdw_mobilewall_event_comment' => 'commented the event {event_caption}',
'_ibdw_mobilewall_event_edit' => 'changed the event {event_caption}',
'_ibdw_mobilewall_share_asdaction' => 'shared the ad {ads_caption}',
'_ibdw_mobilewall_share_videoaction' => 'shared the video {video_caption}',
'_ibdw_mobilewall_share_photoaction' => 'shared the photo {photo_caption}',
'_ibdw_mobilewall_share_groupaction' => 'shared the group {group_caption}',
'_ibdw_mobilewall_share_siteaction' => 'shared the site {site_caption}',
'_ibdw_mobilewall_share_eventaction' => 'shared the event {event_caption}',
'_ibdw_mobilewall_share_pollaction' => 'shared the poll {poll_caption}',
'_ibdw_mobilewall_poll_add' => 'added a Poll {poll_caption}',
'_ibdw_mobilewall_delete' => 'Delete',
'_ibdw_mobilewall_cmnt' => 'Comment',
'_ibdw_mobilewall_likes' => 'Like',
'_ibdw_mobilewall_likes2' => '',
'_ibdw_mobilewall_insertcmnt' => 'Insert Comment',
'_ibdw_mobilewall_send' => 'Send',
'_ibdw_mobilewall_unlike' => 'Unlike',
'_ibdw_mobilewall_close' => 'Close',
'_ibdw_mobilewall_now' => 'now added',
'_ibdw_mobilewall_oneminute' => 'about one minute ago',
'_ibdw_mobilewall_plusminutefirst' => 'about ',
'_ibdw_mobilewall_plusminutesecond' => ' minutes ago',
'_ibdw_mobilewall_onehour' => 'about 1 hour ago',
'_ibdw_mobilewall_plushourfirst' => 'about ',
'_ibdw_mobilewall_plushoursecond' => ' hours ago',
'_ibdw_mobilewall_today' => 'today',
'_ibdw_mobilewall_yesterday' => 'yesterday',
'_ibdw_mobilewall_otherday' => 'added ',
'_ibdw_mobilewall_now' => 'now added',
'_ibdw_mobilewall_dateprev' => '',
'_ibdw_mobilewall_personalwall' => 'What are you thinking?',
'_ibdw_mobilewall_photogo' => 'Photo',
'_ibdw_mobilewall_reload' => 'Reload',
'_ibdw_mobilewall_share_album' => 'shared the album {album_caption}',
'bx_mobilewall_photo_deluxe_commentofoto' => 'commented the photo of {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentofotomsg' => 'commented the photo <b>{album_caption}</b> of {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_tag' => 'was tagged in the photo {album_caption} by {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentoalbummsg' => 'commented the album <b>{album_caption}</b> of {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentoalbum' => 'commented the Album of {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_tag_title' => 'was tagged in the photo "{album_caption}" by {recipient_nick}',
'_ibdw_mobilewall_activaintro' => 'Mobilewall activation procedure',  
'_ibdw_mobilewall_activyes' => 'Your Mobilewall is now active! <br/> Redirect to Administration Area', 
'_ibdw_mobilewall_activno' => 'This code is not valid <br/> Redirect to Administration Area',         
'_ibdw_mobilewall_spycodereq' => 'activation code request',
'_ibdw_mobilewall_yosattiva' => 'Attention, your copy of Mobilewall is already active!',
'_ibdw_mobilewall_introattivazione' => 'IN ORDER TO ACTIVATE Mobilewall IS NEEDED TO ENTER THE EMAIL ADRESS PAYPAL/ECHECK USED FOR PURCHASE THIS MODULE AND THEN CLICK \'\'SEND CODE REQUEST\'\'. YOU WILL RECEIVE AN EMAIL AT THIS ADDRESS CONTAINING THE ACTIVATION CODE. THEN YOU MUST INSERT THIS CODE AND CLICK THE BUTTON ACTIVATE',
'_ibdw_mobilewall_entrecode' => 'Enter below the activation code',
'_ibdw_mobilewall_emailconferma' =>'The request was submitted properly, you will receive an email from info@ilbellodelweb.it with the subject \'\'activation SpyWall\'\' containing all informations. The email has been sent to:', 
'_ibdw_mobilewall_emailconferma2' =>'Now we can check your payment corrisponding at this email - If your dont receive the email within 48h, please contact us at info@ilbellodelweb.it', 
'_ibdw_mobilewall_sostituiscibott' => 'To replace the button "Active Mobilewall" in "Mobilewall Config" click here!',
'_ibdw_mobilewall_infocoferma1' => 'Are you sure this is the email',
'_ibdw_mobilewall_infocoferma2' => 'you have used to pay?',
'_ibdw_mobilewall_act_t_code' => 'ACTIVATION CODE',
'_ibdw_mobilewall_1step' => 'Step 1',
'_ibdw_mobilewall_2step' => 'Step 2',
'_ibdw_mobilewall_eml_t_add' => 'Insert your email address (Paypal/Echeck)',
'_ibdw_mobilewall_ins_t_code' => 'Insert the activation code you received via email',
'_ibdw_mobilewall_send_rqs' => 'Send Request',
'_ibdw_mobilewall_conf_1' => 'ACTIVATE',	
'_ibdw_mobilewall_conf_email_pay' => 'CONFIRM AND REQUIRE THE ACTIVACTION CODE',
'_ibdw_mobilewall_sicurity' => 'Your version of Mobilewall is not active, go to the administration area and complete the activation procedure. This message is visible only to administrator',
'_ibdw_mobilewall_updater' => 'Update completed successfully',
'_ibdw_mobilewall_backadmin' => 'Return to main administration',
'_ibdw_mobilewall_backspyconfig' => 'Return to Mobilewall Configuration',
'_ibdw_mobilewall_backspymainactive' => 'Return to Activation Procedure',
'_ibdw_mobilewall_sharefun' => 'Share',
'_ibdw_mobilewall_see_more' => 'See more',
'_idbw_mobilewall_member_news' => 'News Feed',
'_ibdw_mobilewall_comment_add' => 'commented the profile'
);