<?
/**********************************************************************************
*                            IBDW MobileWall Dolphin Smart Community Builder
*                              -------------------
*     begin                : Oct 18 2011
*     copyright            : (C) 2011 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW MobileWall is not free and you cannot redistribute and/or modify it.
* 
* IBDW MobileWall is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'mobilewall';
$aLangContent = array(
'_ibdw_mobilewall_member_subscribed' => 'si è  iscritto',
'_ibdw_mobilewall_spyprofile' => 'ha visto il profilo {recipient_p_nick}',
'_ibdw_mobilewall_profile_edit' => 'ha cambiato il proprio profilo',
'_ibdw_mobilewall_profile_rate' => 'ha votato il profilo {recipient_p_nick}',
'_ibdw_mobilewall_isfriend' => 'ha stretto amicizia con {recipient_p_nick}',
'_ibdw_mobilewall_site_edit' => 'ha modificato il sito {site_caption}',
'_ibdw_mobilewall_site_rate' => 'ha modificato il sito {site_caption}',
'_ibdw_mobilewall_site_comment' => 'ha commentato il sito {site_caption}',	
'_ibdw_mobilewall_comment_nphoto' => 'ha commentato la foto di {recipient_p_nick}',
'_ibdw_mobilewall_comment_name' => 'ha commentato il video di {recipient_p_nick}',
'_ibdw_mobilewall_rated_videos' => 'ha votato il video di {recipient_p_nick}',
'_ibdw_mobilewall_reply_polls' => 'ha risposto al sondaggio di {recipient_p_nick}',
'_ibdw_mobilewall_rated_polls' => 'ha votato il sondaggio di {recipient_p_nick}',
'_ibdw_mobilewall_comment_polls' => 'ha commentato il sondaggio di {recipient_p_nick}',
'_ibdw_mobilewall_rate_photo' => 'ha votato la foto di {recipient_p_nick}',
'_ibdw_mobilewall_ads_rate' => 'ha votato l\'annuncio {ads_caption}',
'_ibdw_mobilewall_ads_add' => 'ha aggiunto un nuovo annuncio {ads_caption}',
'_ibdw_mobilewall_photo_add' => 'ha aggiunto una nuova foto {photo_caption}',
'_ibdw_mobilewall_video_add' => 'ha aggiunto un nuovo video {video_caption}',
'_ibdw_mobilewall_site_add' => 'ha aggiunto un nuovo sito {site_caption}',
'_ibdw_mobilewall_group_add' => 'ha creato il gruppo {group_caption}',
'_ibdw_mobilewall_group_editaw' => 'ha modificato il gruppo {group_caption}',
'_ibdw_mobilewall_group_join' => 'si è  iscritto al gruppo {group_caption}',
'_ibdw_mobilewall_group_rate' => 'ha votato il gruppo {group_caption}', 
'_ibdw_mobilewall_group_comment' => 'ha commentato sul gruppo {group_caption}',
'_ibdw_mobilewall_event_add' => 'ha aggiunto un nuovo evento {event_caption}',
'_ibdw_mobilewall_event_join' => 'partecipa all\'evento {event_caption}',
'_ibdw_mobilewall_event_rate' => 'ha votato l\'evento {event_caption}',
'_ibdw_mobilewall_event_comment' => 'ha commentato l\'evento {event_caption}',
'_ibdw_mobilewall_event_edit' => 'ha modificato l\'evento {event_caption}',
'_ibdw_mobilewall_share_asdaction' => 'ha condiviso l\'annuncio {ads_caption}',
'_ibdw_mobilewall_share_videoaction' => 'ha condiviso il video {video_caption}',
'_ibdw_mobilewall_share_photoaction' => 'ha condiviso la foto {photo_caption}',
'_ibdw_mobilewall_share_groupaction' => 'ha condiviso il gruppo {group_caption}',
'_ibdw_mobilewall_share_siteaction' => 'ha condiviso il sito {site_caption}',
'_ibdw_mobilewall_share_eventaction' => 'ha condiviso l\'evento {event_caption}',
'_ibdw_mobilewall_share_pollaction' => 'ha condiviso il sondaggio {poll_caption}',
'_ibdw_mobilewall_poll_add' => 'ha aggiunto il sondaggio {poll_caption}',
'_ibdw_mobilewall_delete' => 'Cancella',
'_ibdw_mobilewall_cmnt' => 'Commenta',
'_ibdw_mobilewall_likes' => 'Mi piace',
'_ibdw_mobilewall_likes2' => '',
'_ibdw_mobilewall_insertcmnt' => 'Inserisci Commento',
'_ibdw_mobilewall_send' => 'Invia',
'_ibdw_mobilewall_unlike' => 'Non mi piace più',
'_ibdw_mobilewall_close' => 'Chiudi',
'_ibdw_mobilewall_now' => 'aggiunto adesso',
'_ibdw_mobilewall_oneminute' => 'circa un minuto fa',
'_ibdw_mobilewall_plusminutefirst' => 'circa ',
'_ibdw_mobilewall_plusminutesecond' => ' minuti fa',
'_ibdw_mobilewall_onehour' => 'circa 1 ora fa',
'_ibdw_mobilewall_plushourfirst' => 'circa ',
'_ibdw_mobilewall_plushoursecond' => ' ore fa',
'_ibdw_mobilewall_today' => 'oggi',
'_ibdw_mobilewall_yesterday' => 'ieri',
'_ibdw_mobilewall_otherday' => 'aggiunto ',
'_ibdw_mobilewall_now' => 'aggiunto adesso',
'_ibdw_mobilewall_dateprev' => '',
'_ibdw_mobilewall_personalwall' => 'Cosa stai pensando?',
'_ibdw_mobilewall_photogo' => 'Foto',
'_ibdw_mobilewall_reload' => 'Ricarica',
'_ibdw_mobilewall_share_album' => 'ha condiviso l\'album {album_caption}',
'bx_mobilewall_photo_deluxe_commentofoto' => 'ha commentato la foto di {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentofotomsg' => 'ha commentato la foto <b>{album_caption}</b> of {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_tag' => 'ricevuto un tag nella foto {album_caption} da {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentoalbummsg' => 'ha commentato l\'album <b>{album_caption}</b> di {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_commentoalbum' => 'ha commentato l\'album di {recipient_p_nick}',
'bx_mobilewall_photo_deluxe_tag_title' => 'ha ricevuto un tag nella foto "{album_caption}" da {recipient_nick}',
'_ibdw_mobilewall_activaintro' => 'Mobilewall activation procedure',  
'_ibdw_mobilewall_activyes' => 'Your Mobilewall is now active! <br/> Redirect to Administration Area', 
'_ibdw_mobilewall_activno' => 'This code is not valid <br/> Redirect to Administration Area',         
'_ibdw_mobilewall_spycodereq' => 'activation code request',
'_ibdw_mobilewall_yosattiva' => 'Attention, your copy of Mobilewall is already active!',
'_ibdw_mobilewall_introattivazione' => 'IN ORDER TO ACTIVATE Mobilewall IS NEEDED TO ENTER THE EMAIL ADRESS PAYPAL/ECHECK USED FOR PURCHASE THIS MODULE AND THEN CLICK \'\'SEND CODE REQUEST\'\'. YOU WILL RECEIVE AN EMAIL AT THIS ADDRESS CONTAINING THE ACTIVATION CODE. THEN YOU MUST INSERT THIS CODE AND CLICK THE BUTTON ACTIVATE',
'_ibdw_mobilewall_entrecode' => 'Enter below the activation code',
'_ibdw_mobilewall_emailconferma' =>'The request was submitted properly, you will receive an email from info@ilbellodelweb.it with the subject \'\'activation SpyWall\'\' containing all informations. The email has been sent to:', 
'_ibdw_mobilewall_emailconferma2' =>'Now we can check your payment corrisponding at this email - If your dont receive the email within 48h, please contact us at info@ilbellodelweb.it', 
'_ibdw_mobilewall_sostituiscibott' => 'To replace the button "Active Mobilewall" in "Mobilewall Config" click here!',
'_ibdw_mobilewall_infocoferma1' => 'Are you sure this is the email',
'_ibdw_mobilewall_infocoferma2' => 'you have used to pay?',
'_ibdw_mobilewall_act_t_code' => 'ACTIVATION CODE',
'_ibdw_mobilewall_1step' => 'Step 1',
'_ibdw_mobilewall_2step' => 'Step 2',
'_ibdw_mobilewall_eml_t_add' => 'Insert your email address (Paypal/Echeck)',
'_ibdw_mobilewall_ins_t_code' => 'Insert the activation code you received via email',
'_ibdw_mobilewall_send_rqs' => 'Send Request',
'_ibdw_mobilewall_conf_1' => 'ACTIVATE',	
'_ibdw_mobilewall_conf_email_pay' => 'CONFIRM AND REQUIRE THE ACTIVACTION CODE',
'_ibdw_mobilewall_sicurity' => 'Your version of Mobilewall is not active, go to the administration area and complete the activation procedure. This message is visible only to administrator',
'_ibdw_mobilewall_updater' => 'Update completed successfully',
'_ibdw_mobilewall_backadmin' => 'Return to main administration',
'_ibdw_mobilewall_backspyconfig' => 'Return to Mobilewall Configuration',
'_ibdw_mobilewall_backspymainactive' => 'Return to Activation Procedure',
'_ibdw_mobilewall_sharefun' => 'Condividi',
'_ibdw_mobilewall_see_more' => 'Altre News',
'_idbw_mobilewall_member_news' => 'News Feed',
'_ibdw_mobilewall_comment_add' => 'ha commentato il profilo'
);