<?
/**********************************************************************************
*                            IBDW MEGAPROFILE for Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mar 18 2010
*     copyright            : (C) 2010 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW MEGAPROFILE is not free and you cannot redistribute and/or modify it.
* 
* IBDW MEGAPROFILE is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details see license.txt file; if not, write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'megaprofile';
$aLangContent = array(
'_ibdw_megaprofile_modulename' => 'Profile',
'_ibdw_mp_changepic' => 'Change Picture',
'_ibdw_mp_calbum' => 'From the album',
'_ibdw_mp_cpc' => 'Upload',
'_ibdw_mp_photofme' => 'View Photos of Me',
'_ibdw_mp_videofme' => 'View Videos of Me',
'_ibdw_mp_editme' => 'Edit My Profile',
'_ibdw_mp_photof' => 'View {NickName}\'s Photos',
'_ibdw_mp_videof' => 'View {NickName}\'s Videos',
'_ibdw_mp_sendmsg' => 'Send a Message',
'_ibdw_mp_greetings' => 'Greetings',
'_ibdw_mp_spamrep' => 'Report Spam',
'_ibdw_mp_befriend' => 'Befriend',
'_ibdw_mp_removefriend' => 'Remove Friend',
'_ibdw_mp_block' => 'Block',
'_ibdw_mp_unblock' => 'Unblock',
'_ibdw_mp_fave' => 'Fave',
'_ibdw_mp_subs' => 'Subscribe',
'_ibdw_mp_unsubs' => 'Unsubscribe',
'_ibdw_mp_infos' => 'Informations',
'_ibdw_mp_salva' => 'Save',
'_ibdw_mp_annulla' => 'Cancel',
'_ibdw_mp_relst' => 'Relationship Status:',
'_ibdw_mp_brt' => 'Date of Birth:',
'_ibdw_mp_bd' => 'Birthday:',
'_ibdw_mp_city' => 'Current City:',
'_ibdw_mp_headline' => 'Headline:',
'_ibdw_mp_mutual' => 'Mutual Friends',
'_ibdw_mp_mutual2' => 'friends in common',
'_ibdw_mp_friends' => 'Friends',
'_ibdw_mp_friends2' => 'Friend',
'_ibdw_mp_friends3' => 'Friends',
'_ibdw_mp_all' => 'See All',
'_ibdw_mp_readmore' => 'Read more',
'_ibdw_mp_collapse' => 'Collapse',
'_ibdw_mp_aphotos' => 'Photos',
'_ibdw_mp_avideos' => 'Videos',
'_ibdw_mp_ofalbums' => '{numberofalbum} of {numeroallalbum} Albums',
'_ibdw_mp_rphotos' => '<span class="grass">{numphotos}</span> photos',
'_ibdw_mp_rvideos' => '<span class="grass">{numvideos}</span> videos',
'_ibdw_mp_customize' => 'Customize',
'_ibdw_mp_fave' => 'Fave',
'_ibdw_mp_email' => 'Email:',
'_ibdw_mp_sex' => 'Sex:',
'_ibdw_mp_sexmale' => 'Male',
'_ibdw_mp_sexfemale' => 'Female',
'_ibdw_mp_lookingfor' => 'Looking for:',
'_ibdw_mp_lookingformalefemale' => 'male, female',
'_ibdw_mp_lookingformale' => 'male',
'_ibdw_mp_lookingforfemale' => 'female',
'_ibdw_mp_occupation' => 'Occupation:',
'_ibdw_mp_religion' => 'Religion:',
'_ibdw_mp_cropp' => 'Crop image',
'_ibdw_mp_cropintro' => 'If you want you can crop an image and set it as your avatar otherwise you can simple set it only as your profile image.',
'_ibdw_mp_savecrop' => 'Crop and Save',
'_ibdw_mp_cancellcrop' => 'Save without crop',
'_ibdw_mp_cropandavatar' => 'Set as avatar',
'_ibdw_mp_ritagliamenu' => 'Crop image',
'_ibdw_mp_ritsetava' => 'Set as avatar',
'_ibdw_mp_activaintro' => 'MegaProfile activation procedure',  
'_ibdw_mp_activyes' => 'MegaProfile is now active! <br/>Administration redirect', 
'_ibdw_mp_activno' => 'This code is not valid <br/>Back to the Administration',         
'_ibdw_mp_spycodereq' => 'Activation code request',
'_ibdw_mp_yosattiva' => 'Attention! The mod MegaProfile is already active!',
'_ibdw_mp_introattivazione' => 'To require the activation code you must enter the email address (PayPal/ECheck) used to buy (It\'s important you use the same address used to pay, otherwise we can\'t verify your payment and generate the activation code)',
'_ibdw_mp_infocoferma1' => 'Are you sure this is the email address (',
'_ibdw_mp_infocoferma2' => ') you used to pay?',
'_ibdw_mp_entrecode' => 'Insert here the activaction code',
'_ibdw_mp_emailconferma' =>'The request was submitted properly, you will receive an email from info@ilbellodelweb.it with 
    the subject \'\'activation MegaProfile\'\' containing all the informations. The email has been sent to:', 
'_ibdw_mp_emailconferma2' =>'Now we can check if your payment email is the same you have specified here - If your dont receive the email within 48h, please contact us at info@ilbellodelweb.it', 
'_ibdw_mp_sostituiscibott' => 'Delete button "Active MegaProfile"!',
'_ibdw_mp_altrobottone' => 'Other',
'_ibdw_mp_backadmin' => 'Return to Administration',
'_ibdw_mp_takeweb' => 'Take webCam',
'_ibdw_mp_removeimg' => 'Remove image',
'_ibdw_mp_errorfriend' => 'Warning: this request was already sent',
'_ibdw_mp_friendrequ' => 'The request was sent',
'_ibdw_mp_frompc' => 'Choose an image from your computer',
'_ibdw_mp_introfrompc' => 'you can upload only Jpeg, Gif and Png images.',
'_ibdw_mp_sg1' => 'Dont use big images.',
'_ibdw_mp_sg2' => 'Respect the copyright.',
'_ibdw_mp_sg3' => 'Make sure the image is ethical.',
'_ibdw_mp_sg4' => 'Dont load images offensive.',
'_ibdw_mp_wksg1' => 'Wait the webcam inizialization.',
'_ibdw_mp_wksg2' => 'Allows the connection.',
'_ibdw_mp_wksg3' => 'take the picture.',
'_ibdw_mp_wksg4' => 'When you are convinced of the captured image click "Continue", otherwise "Remove"',
'_ibdw_mp_wkcnt' => 'Continue',
'_ibdw_mp_selectalbum' => 'Choose a photo from your album',
'_ibdw_mp_backspymainactive' => 'Back to the activation',
'_ibdw_mp_selectcrop' => 'Select part to crop',
'_ibdw_mp_age' => 'Age:',
'_ibdw_mp_age2' => 'years',
'_ibdw_mp_firstinfos' => 'Info First Person',
'_ibdw_mp_secondinfos' => 'Info Second Person',
'_ibdw_mp_givecredits' => 'Give Credits',
'_ibdw_mp_sshare' => 'Share',
'_ibdw_mp_invitefriend' => 'Invite Friend',
'_ibdw_mp_donatefeatured' => 'Donate Featured',
'_ibdw_mp_sendgift' => 'Send Gift',
'_ibdw_mp_follow' => 'Follow',
'_ibdw_mp_unfollow' => 'UnFollow',
'_ibdw_mp_sendpoke' => 'Send Poke',
'_ibdw_mp_getemail' => 'Get Email',
'_ibdw_mp_donatepoints' => 'Donate Points',
'_ibdw_mp_challenge' => 'Challenge',
'_ibdw_mp_donatecredits' => 'Donate Credits',
'_ibdw_mp_makespotlighted' => 'Make Spotlighted',
'_ibdw_mp_sicurity'=> 'Your version of MegaProfile is not active, go to the administration area and complete the activation procedure. This message is visible only to the administrator',
'_ibdw_mp_vdzone' => 'Video Zone',
'_ibdw_mp_sendtags' => 'Send Tags',
'_ibdw_mp_sendflirt' => 'Send Flirt',
'_ibdw_mp_videochat' => 'Video Chat',
'_ibdw_mp_playgames' => 'Play Games',
'_ibdw_mp_pdxext' => 'Edit photo',
'_ibdw_mp_playpets' => 'Play Pets',
'_ibdw_mp_chatwith' => 'Chat with {ProfileName}...',
'_ibdw_mp_soundofme' => 'Sounds of me',
'_ibdw_mp_soundof' => '{NickName}\'s Sounds',
'_ibdw_mp_selectfiles' => 'Select Files',
);             