<?
/**********************************************************************************
*                            IBDW MEGAPROFILE for Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mar 18 2010
*     copyright            : (C) 2010 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW MEGAPROFILE is not free and you cannot redistribute and/or modify it.
* 
* IBDW MEGAPROFILE is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details see license.txt file; if not, write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'megaprofile';
$aLangContent = array(
'_ibdw_megaprofile_modulename' => 'Profilo',
'_ibdw_mp_changepic' => 'Cambia Foto',
'_ibdw_mp_calbum' => 'Dall\'album',
'_ibdw_mp_cpc' => 'Carica',
'_ibdw_mp_photofme' => 'Foto del mio profilo',
'_ibdw_mp_videofme' => 'Video del mio profilo',
'_ibdw_mp_editme' => 'Modifica il profilo',
'_ibdw_mp_photof' => 'Guarda le foto di {NickName}',
'_ibdw_mp_videof' => 'Guarda i video di {NickName}',
'_ibdw_mp_sendmsg' => 'Invia un messaggio',
'_ibdw_mp_greetings' => 'Saluta',
'_ibdw_mp_spamrep' => 'Segnala abuso',
'_ibdw_mp_befriend' => 'Richiedi amicizia',
'_ibdw_mp_removefriend' => 'Rimuovi dagli amici',
'_ibdw_mp_block' => 'Blocca',
'_ibdw_mp_unblock' => 'Sblocca',
'_ibdw_mp_fave' => 'Preferito',
'_ibdw_mp_subs' => 'Sottoscrivi il profilo',
'_ibdw_mp_unsubs' => 'Rimuovi sottoscrizione',
'_ibdw_mp_infos' => 'Informazioni',
'_ibdw_mp_salva' => 'Salva',
'_ibdw_mp_annulla' => 'Annulla',
'_ibdw_mp_relst' => 'Situazione sentimentale:',
'_ibdw_mp_brt' => 'Data di nascita:',
'_ibdw_mp_bd' => 'Compleanno:',
'_ibdw_mp_city' => 'Città in cui ti trovi:',
'_ibdw_mp_headline' => 'Motto:',
'_ibdw_mp_mutual' => 'Amici in comune',
'_ibdw_mp_mutual2' => 'amici in comune',
'_ibdw_mp_friends' => 'Amici',
'_ibdw_mp_friends2' => 'Amico',
'_ibdw_mp_friends3' => 'Amici',
'_ibdw_mp_readmore' => 'Leggi tutto',
'_ibdw_mp_collapse' => 'Comprimi',
'_ibdw_mp_all' => 'Vedi tutto',
'_ibdw_mp_aphotos' => 'Foto',
'_ibdw_mp_avideos' => 'Video',
'_ibdw_mp_ofalbums' => '{numberofalbum} di {numeroallalbum} Album',
'_ibdw_mp_rphotos' => '<span class="grass">{numphotos}</span> foto',
'_ibdw_mp_rvideos' => '<span class="grass">{numvideos}</span> video',
'_ibdw_mp_customize' => 'Personalizza',
'_ibdw_mp_fave' => 'Preferito',
'_ibdw_mp_email' => 'Email:',
'_ibdw_mp_sex' => 'Sesso:',
'_ibdw_mp_sexmale' => 'Maschio',
'_ibdw_mp_sexfemale' => 'Femmina',
'_ibdw_mp_lookingfor' => 'Visibile per:',
'_ibdw_mp_lookingformalefemale' => 'maschio, femmina',
'_ibdw_mp_lookingformale' => 'maschio',
'_ibdw_mp_lookingforfemale' => 'femmina',
'_ibdw_mp_occupation' => 'Occupazione:',
'_ibdw_mp_religion' => 'Religione:',
'_ibdw_mp_cropp' => 'Ritaglia immagine',
'_ibdw_mp_cropintro' => 'Puoi scegliere se ritagliare l\'immagine e impostarla come avatar.',
'_ibdw_mp_savecrop' => 'Ritaglia e salva',
'_ibdw_mp_cancellcrop' => 'Continua senza ritagliare',
'_ibdw_mp_cropandavatar' => 'Imposta come avatar',
'_ibdw_mp_ritagliamenu' => 'Ritaglia immagine',
'_ibdw_mp_ritsetava' => 'Imposta come avatar',
'_ibdw_mp_activaintro' => 'MegaProfile activation procedure',  
'_ibdw_mp_activyes' => 'MegaProfile is now active! <br/>Administration redirect', 
'_ibdw_mp_activno' => 'This code is not valid <br/>Back to the Administration',         
'_ibdw_mp_spycodereq' => 'Activation code request',
'_ibdw_mp_yosattiva' => 'Attention! The mod MegaProfile is already active!',
'_ibdw_mp_introattivazione' => 'To require the activation code you must enter the email address (PayPal/ECheck) used to buy (It\'s important you use the same address used to pay, otherwise we can\'t verify your payment and generate the activation code)',
'_ibdw_mp_infocoferma1' => 'Are you sure this is the email address (',
'_ibdw_mp_infocoferma2' => ') you used to pay?',
'_ibdw_mp_entrecode' => 'Insert here the activaction code',
'_ibdw_mp_emailconferma' =>'The request was submitted properly, you will receive an email from info@ilbellodelweb.it with 
    the subject \'\'activation MegaProfile\'\' containing all the informations. The email has been sent to:', 
'_ibdw_mp_emailconferma2' =>'Now we can check if your payment email is the same you have specified here - If your dont receive the email within 48h, please contact us at info@ilbellodelweb.it', 
'_ibdw_mp_sostituiscibott' => 'Delete button "Active MegaProfile"!',
'_ibdw_mp_altrobottone' => 'Altro',
'_ibdw_mp_backadmin' => 'Return to Administration',
'_ibdw_mp_takeweb' => 'Scatta da webCam',
'_ibdw_mp_removeimg' => 'Rimouovi immagine',
'_ibdw_mp_errorfriend' => 'Attenzione: richiesta già inviata',
'_ibdw_mp_friendrequ' => 'Richiesta inviata',
'_ibdw_mp_frompc' => 'Scegli una immagine dal tuo PC',
'_ibdw_mp_introfrompc' => 'puoi caricare solo immnagini Jpeg, Gif and Png.',
'_ibdw_mp_sg1' => 'Non usare immagini di grandi dimensioni.',
'_ibdw_mp_sg2' => 'Rispetta il diritto d\'autore.',
'_ibdw_mp_sg3' => 'Carica immagini consentite.',
'_ibdw_mp_sg4' => 'Non caricare immagini offensive.',
'_ibdw_mp_wksg1' => 'Attendi la connessione alla webcam.',
'_ibdw_mp_wksg2' => 'Consenti l\'accesso alla webcam.',
'_ibdw_mp_wksg3' => 'Scatta la foto.',
'_ibdw_mp_wksg4' => 'Se sei convinto clicca su "Continua" altrimenti rimuovi la foto',
'_ibdw_mp_wkcnt' => 'Continua',
'_ibdw_mp_selectalbum' => 'Scegli una foto dall\'album',
'_ibdw_mp_backspymainactive' => 'Back to the activation',
'_ibdw_mp_link1' => 'Link 1',
'_ibdw_mp_link2' => 'Link 2',
'_ibdw_mp_link3' => 'Link 3',
'_ibdw_mp_link4' => 'Link 4',
'_ibdw_mp_link5' => 'Link 5',
'_ibdw_mp_selectcrop' => 'Seleziona la parte da ritagliare',
'_ibdw_mp_age' => 'Età:',
'_ibdw_mp_age2' => 'anni',
'_ibdw_mp_firstinfos' => 'Info prima persona',
'_ibdw_mp_secondinfos' => 'Info seconda persona',
'_ibdw_mp_givecredits' => 'Ottieni Crediti',
'_ibdw_mp_sshare' => 'Condividi',
'_ibdw_mp_invitefriend' => 'Invita un Amico',
'_ibdw_mp_donatefeatured' => 'Dona a Preferito',
'_ibdw_mp_sendgift' => 'Invia un Dono',
'_ibdw_mp_follow' => 'Segui',
'_ibdw_mp_unfollow' => 'Non seguire',
'_ibdw_mp_sendpoke' => 'Invia un Poke',
'_ibdw_mp_getemail' => 'Ottieni Email',
'_ibdw_mp_donatepoints' => 'Dona Punti',
'_ibdw_mp_challenge' => 'Challenge',
'_ibdw_mp_donatecredits' => 'Dona Crediti',
'_ibdw_mp_makespotlighted' => 'Fai Spotlight',
'_ibdw_mp_pdxext' => 'Modifica foto',
'_ibdw_mp_sicurity'=> 'La tua versione di MegaProfile non e\' ancora stata attivata, vai in amministrazione e completa la procedura di attivazione. Questo messaggio � visibile solo all\'amministratore.',
'_ibdw_mp_chatwith' => 'Chatta con {ProfileName}...',
'_ibdw_mp_soundofme' => 'Musiche del mio profilo',
'_ibdw_mp_soundof' => 'Musiche di {NickName}',
'_ibdw_mp_selectfiles' => 'Seleziona File',
);