<?
/***************************************************************************
*                            Dolphin Smart Community Builder
*                              -------------------
*     begin                : Mon Mar 23 2006
*     copyright            : (C) 2007 BoonEx Group
*     website              : http://www.modloaded.com
* This file is part of Dolphin - Smart Community Builder
*
* Dolphin is free software; you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the
* Free Software Foundation; either version 2 of the
* License, or  any later version.
*
* Dolphin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Dolphin,
* see license.txt file; if not, write to marketing@modloaded.com
***************************************************************************/

$sLangCategory = 'Modloaded Pages';

$aLangContent = array(
	'_ml_pages_adm_fields_attribute' => 'Attribute',
	'_ml_pages_adm_fields_attribute_desc' => 'Can be multiplyable or multiplyable with add on',
	'_ml_pages_adm_fields_add_on' => 'Add On',
	'_ml_pages_adm_fields_add_on_desc' => 'Add a new entry',
	'_ml_pages_adm_fields_media_type' => 'Extras',
	'_ml_pages_adm_fields_media_type_desc' => 'Media are multiplyable already, while log extras are hidden. Log is not visible on form only on view, it will record the editor and date',
	'_ml_pages_form_find' => 'Find',
	'_ml_pages_adm_fields_default_desc' => 'Default value set into database(!) if not set by user. Non-mandatory. For boolean fields use 0 or 1. For dates use format: YYYY-MM-DD. For parent field use it\'s own ID Field, for child field, use the Parent\'s ID Field',
	'_ml_pages_adm_fields_default' => 'Default value',
	'_ml_pages_adm_fields_values' => 'Possible values',
	'_ml_pages_adm_fields_values_desc' => 'Use new lines for divider, you can also use predefined values i.e. #!Countries or a table. Just put Values field for the following, categories->sys_categories, privacy->sys_privacy_actions, membership->sys_acl_levels',
	'_ml_pages_adm_fields_with_photo' => 'Google map',
	'_ml_pages_adm_fields_with_photo_desc' => 'Google map field',
	'_ml_pages_adm_fields_id_field' => 'ID Field',
	'_ml_pages_adm_fields_id_field_desc' => 'The ID Field of the table defined in Values field here',
	'_ml_pages_adm_fields_caption_field' => 'Caption Field',
	'_ml_pages_adm_fields_caption_field_desc' => 'The Caption Field of the table defined in Values field here',
	'_ml_pages_adm_fields_dep_field' => 'Child Form Field',
	'_ml_pages_adm_fields_dep_field_desc' => 'The child field of this form. If defined, the child field will depend on this parent field.',
	'_ml_pages_adm_fields_dep_parent_field' => 'Parent Field ID',
	'_ml_pages_adm_fields_dep_parent_field_desc' => 'Defined only if this field is child.',	
	'_ml_pages_block_pages_categories' => 'Categories',
	'_ml_pages_no_website_found' => 'No website found',
	'_ml_page_page_width_invalid' => 'Website page width should be numeric',
	'_ml_pages_page_width_info' => 'Width of the website page view',
	'_ml_pages_website_page_width' => 'Website Page Width',
	'_ml_pages_menu_view_website_settings' => 'Website Settings',
	'_ml_pages_block_embed' => 'Embed Code',
	'_ml_page_website' => 'Website',
	'_ml_pages_website_save' => 'Save',
	'_ml_pages_website' => 'Website',
	'_ml_pages_website_width' => 'frame width',
	'_ml_pages_website_height' => 'frame height',
	'_ml_pages_action_page_events' => '{0} Events',
	'_ml_pages_categ_del_event' => 'Delete Page Event',
	'_ml_pages_caption_events' => 'Events',
	'_ml_page_no_event_found' => 'No events to be added. Please <a href="{0}m/events/browse/my&bx_events_filter=add_event">create</a> an event',
	'_ml_page_no_event_added' => 'No events found. Please <a href="{0}m/pages/add_events/{1}">add</a> a created event',
	'_ml_pages_categ_add_event' => 'Add Event',
	'_ml_page_website_invalid' => 'Should be valid url, like http://example.com',
	'_ml_page_website_info' => 'Should be valid url, like http://example.com',
		'_ml_pages_height_info' => 'Frame height, must be numeric',
	'_ml_pages_width_info' => 'Frame width, must be numeric',
	'_ml_page_website_save' => 'Saved',
	'_ml_pages_action_add_event' => 'Add Event',
	'_ml_pages_action_add_website' => 'Add Website',
	'_ml_pages_menu_view_events' => 'Events',
	'_ml_pages_menu_view_website' => 'Website',
	'_ml_pages_block_events' => 'Events',
	'_ml_pages_block_website' => 'Website',
	'_ml_pages_block_location' => 'Location',
	'_ml_pages_button_select' => 'Select',
	'_ml_pages_upload_not_allowed' => '{0} upload not allowed',
	'_ml_pages_menu_view_location' => 'Location',
	'_ml_pages_form_find' => 'Find',
	'_ml_pages_action_page_location' => '{0} Location',
	'_ml_pages_action_page_no_location' => 'No Location',
	'_ml_pages_form_save' => 'Save',
	'_ml_pages_closest_matching_address' => 'Address',
	'_ml_pages_current_position' => 'Global position',
	'_ml_pages_FieldCaption_Tags_View' => 'Tags',
	'_ml_pages_people_is_fan_of' => 'people is fan of',
	'_ml_pages_total_fans' => 'total fans',
	'_ml_pages_find_us_on' => 'Find us on',
	'_ml_pages_show_embed_code' => 'Show embed code',
	'_ml_pages_block_embed' => 'Embed Code',
	'_ml_pages_adm_fields_link' => 'Link',
	'_ml_pages_adm_fields_link_desc' => 'Field for websites or other links',
	'_ml_pages_adm_fields_with_photo_desc' => 'Field with photo',
	'_ml_pages_add text here' => 'Add text here...',
	'_ml_pages_set_as_thumb' => 'set as thumb',
	'_ml_pages_page_logo' => 'Page Logo',
	'_ml_pages_FieldCaption_PrimPhoto_Join' => 'Page Photo',
	'_ml_pages_adm_fields_with_photo' => 'With Photo',
	'_ml_page_delete_photo_field' => 'Delete',
	'_ml_pages_action_embed_videos' => 'Embed videos',
	'_ml_page_unordered' => 'Unordered',
	'_ml_page_ordered' => 'Ordered',
	'_ml_page_field_photo' => 'Photo',
	'_ml_page_adm_fields_multiplecss' => 'Multipe display css',
	'_ml_page_adm_fields_multiplecss_desc' => 'For multiple display style customization',
	'_ml_page_adm_fields_multiplestyle' => 'Display style',
	'_ml_page_adm_fields_multiplestyle_desc' => 'This is only applicable when multiplyable is checked. Photo is available when this field has field photo exists and is active on the view page',
	'_ml_pages_disable_caption' => 'Disable caption',
	'_ml_pages_disable_caption_desc' => 'This will disable the caption on page view',
	'_ml_pages_box_height' => 'Box height',
	'_ml_pages_box_height_desc' => 'Creates a fixed height and enable scrolling, numeric only',
	'_ml_page_adm_fields_photofor' => 'Photo For Field',
	'_ml_page_adm_fields_photofor_desc' => 'Add photo on selected field on page view',
	'_ml_page_adm_fields_multiplyabl_desc' => 'Enable multiple inputs',
	'_ml_page_no_media_found' => 'No {0} found',
	'_ml_page_adm_fields_multiplyable' => 'Multiplyable',
	'_ml_page_photos' => '{0}\'s page photos',
	'_ml_page_sounds' => '{0}\'s page sounds',
	'_ml_page_videos' => '{0}\'s page videos',
	'_ml_page_files' => '{0}\'s page files',
	'_ml_page_photo_album' => '{0}\'s page photo album',
	'_ml_page_video_album' => '{0}\'s page video album',
	'_ml_page_sound_album' => '{0}\'s page sound album',
	'_ml_page_file_album' => '{0}\'s page file album',
	'_ml_pages_FieldCaption_TermsOfUse_Join' => 'I have read and agreed with <a href="terms_of_use.php" target="_blank">Terms of Use</a>.',
	'_ml_pages_cant_delete_category' => 'Some pages are associated with this category',
	'_ml_pages_select_add' => '--Add--',
	'_ml_pages_categ_caption' => 'Caption',
	'_ml_pages_categ_name' => 'Name',
	'_ml_pages_categ_present_icon' => 'Present Icon',
	'_ml_pages_categ_icon' => 'Icon',
	'_ml_pages_administration_sub_categories' => 'Sub Categories',
	'_ml_pages_administration_main_categories' => 'Main Categories',
	'_ml_pages_main_categories' => 'Main Categories',
	'_ml_pages_categ_btn_update' => 'Update',
	'_ml_pages_categ_btn_delete' => 'Delete',
	'_ml_pages_categ_btn_save' => 'Add',
	'_ml_pages_save profile successful' => 'Page Successfully Saved!',
	'_ml_pages_FieldCaption_Title_Edit' => 'Name',
	'_ml_pages_FieldCaption_Description_Edit' => 'Description',
	'_ml_pages_FieldCaption_Tags_Edit' => 'Tags',
	'_ml_pages_FieldCaption_Title_View' => 'Name',
	'_ml_pages_FieldCaption_Title_Join' => 'Name',
	'_ml_pages_administration_categories' => 'Categories',
	'_ml_pages_back' => 'Back to main',
	'_ml_pages_FieldCaption_EmailNotify_Edit' => 'Receive mass mails',
	'_ml_pages_FieldCaption_Profile Type_Join' => 'Profile type',
	'_ml_pages_FieldCaption_Couple_Join' => 'Profile type',
	'_ml_pages_FieldDesc_Couple_Join' => 'Select "Couple" if you are joining as a couple',
	'_ml_pages_FieldCaption_General Info_Join' => 'General Info',
	'_ml_pages_FieldCaption_NickName_Join' => 'Name',
	'_ml_pages_FieldDesc_Title_Join' => 'Select Name which will be used for logging in to the site',
	'_ml_pages_FieldError_Title_Mandatory' => 'You must enter Name',
	'_ml_pages_FieldError_Title_Min' => 'Your Name must be at least {0} characters long',
	'_ml_pages_FieldError_Title_Max' => 'Your Name should be no longer than {0} characters long',
	'_ml_pages_FieldError_Title_Unique' => 'This Name already used by another. Please select another Name.',
	'_ml_pages_FieldError_Title_Check' => 'Your Name must contain only latin symbols, numbers or underscore ( _ ) or minus ( - ) signs',
	'_ml_pages_FieldCaption_Email_Join' => 'Email',
	'_ml_pages_FieldDesc_Email_Join' => 'Enter your Email. Your password will be sent to this email.',
	'_ml_pages_FieldError_Email_Mandatory' => 'You must enter Email',
	'_ml_pages_FieldError_Email_Min' => 'Your email too short',
	'_ml_pages_FieldError_Email_Unique' => 'Your email already used by another member',
	'_ml_pages_FieldError_Email_Check' => 'Please enter correct email',
	'_ml_pages_FieldCaption_Password_Join' => 'Password',
	'_ml_pages_FieldDesc_Password_Join' => 'Please specify your password. It will be used for logging in to the site. This storage is secure, because we are using an encrypted format.',
	'_ml_pages_FieldError_Password_Mandatory' => 'You must enter password',
	'_ml_pages_FieldError_Password_Min' => 'Your password must be at least {0} characters long',
	'_ml_pages_FieldError_Password_Max' => 'Your password should be no longer than {0} characters',
	'_ml_pages_FieldCaption_Misc Info_Join' => 'Miscellaneous Info',
	'_ml_pages_FieldCaption_Sex_Join' => 'Sex',
	'_ml_pages_FieldDesc_Sex_Join' => 'Please specify your gender',
	'_ml_pages_FieldError_Sex_Mandatory' => 'You must specify your gender',
	'_ml_pages_FieldCaption_LookingFor_Join' => 'Looking for',
	'_ml_pages_FieldDesc_LookingFor_Join' => 'Please specify whom you are looking for',
	'_ml_pages_FieldCaption_DateOfBirth_Join' => 'Date of birth',
	'_ml_pages_FieldDesc_DateOfBirth_Join' => 'Please specify your birth date using the calendar or with this format: Year-Month-Day',
	'_ml_pages_FieldError_DateOfBirth_Mandatory' => 'You must specify your birth date',
	'_ml_pages_FieldError_DateOfBirth_Min' => 'You cannot join the site if you are younger than {0} years',
	'_ml_pages_FieldError_DateOfBirth_Max' => 'You cannot be older than {0} years',
	'_ml_pages_FieldCaption_Headline_Join' => 'Headline',
	'_ml_pages_FieldDesc_Headline_Join' => 'Enter your life headline',
	'_ml_pages_FieldCaption_Description_Join' => 'Description',
	'_ml_pages_FieldDesc_Description_Join' => 'Describe the page in a few words. Your description should be at least {0} characters long.',
	'_ml_pages_FieldError_Description_Mandatory' => 'You must enter your description',
	'_ml_pages_FieldError_DescriptionMe_Min' => 'Your description should be at least 20 characters long',
	'_ml_pages_FieldCaption_Country_Join' => 'Country',
	'_ml_pages_FieldDesc_Country_Join' => 'Please select the country where are you living',
	'_ml_pages_FieldCaption_City_Join' => 'City',
	'_ml_pages_FieldDesc_City_Join' => 'Enter the name of the city where are you living',
	'_ml_pages_FieldCaption_Security Image_Join' => 'Security Image',
	'_ml_pages_FieldCaption_Captcha_Join' => 'Captcha',
	'_ml_pages_FieldDesc_Captcha_Join' => 'Let us check that you are not a bot. Just enter the text which you see on the picture.',
	'_ml_pages_FieldCaption_Admin Controls_Join' => 'Admin Controls',
	'_ml_pages_FieldCaption_Description_Join' => 'Description',
	'_ml_pages_FieldCaption_zip_Join' => 'Post code (Zip)',
	'_ml_pages_FieldDesc_zip_Join' => 'Enter your Post code (Zip)',
	'_ml_pages_FieldCaption_Tags_Join' => 'Tags',
	'_ml_pages_FieldDesc_Tags_Join' => 'Enter a few words delimited by commas that describe your character',
	'_ml_pages_FieldCaption_General Info_Edit' => 'General Info',
	'_ml_pages_FieldCaption_NickName_Edit' => 'Name',
	'_ml_pages_FieldCaption_Email_Edit' => 'Email',
	'_ml_pages_FieldCaption_Sex_Edit' => 'Sex',
	'_ml_pages_FieldCaption_Password_Edit' => 'Change Password',
	'_ml_pages_FieldDesc_Password_Edit' => 'To save old password, just leave this field empty. To change, enter new password and confirm it below.',
	'_ml_pages_FieldCaption_Misc Info_Edit' => 'Misc Info',
	'_ml_pages_FieldCaption_LookingFor_Edit' => 'Looking For',
	'_ml_pages_FieldCaption_DateOfBirth_Edit' => 'Date Of Birth',
	'_ml_pages_FieldCaption_Headline_Edit' => 'Headline',
	'_ml_pages_FieldCaption_DescriptionMe_Edit' => 'Description',
	'_ml_pages_FieldCaption_Country_Edit' => 'Country',
	'_ml_pages_FieldCaption_City_Edit' => 'City',
	'_ml_pages_FieldCaption_Admin Controls_Edit' => 'Admin Controls',
	'_ml_pages_FieldCaption_Status_Edit' => 'Status',
	'_ml_pages_FieldDesc_Status_Edit' => 'System user status',
	'_ml_pages_FieldCaption_Featured_Edit' => 'Featured',
	'_ml_pages_FieldDesc_Featured_Edit' => 'Show this member in "Featured" block of index page',
	'_ml_pages_FieldCaption_allow_view_to_Edit' => 'Profile privacy',
	'_ml_pages_FieldCaption_General Info_View' => 'General Info',
	'_ml_pages_FieldCaption_Misc_View' => 'Misc',
	'_ml_pages_FieldCaption_ID_View' => 'Member ID',
	'_ml_pages_FieldCaption_NickName_View' => 'Name',
	'_ml_pages_FieldCaption_Status_View' => 'Status',
    '_ml_pages_FieldCaption_Sex_View' => 'Sex',
    '_ml_pages_FieldCaption_Age_View' => 'Age',
	'_ml_pages_FieldCaption_LookingFor_View' => 'Looking For',
	'_ml_pages_FieldCaption_Misc Info_View' => 'Misc Info',
	'_ml_pages_FieldCaption_DateOfBirth_View' => 'Date Of Birth',
	'_ml_pages_FieldCaption_Country_View' => 'Country',
	'_ml_pages_FieldCaption_City_View' => 'City',
	'_ml_pages_FieldCaption_Description_View' => 'Description',
	'_ml_pages_FieldCaption_Headline_View' => 'Headline',
	'_ml_pages_FieldCaption_DescriptionMe_View' => 'Description',
	'_ml_pages_FieldCaption_Admin Controls_View' => 'Admin Controls',
	'_ml_pages_FieldCaption_Email_View' => 'Email',
	'_ml_pages_FieldCaption_DateReg_View' => 'Registration Date',
	'_ml_pages_FieldCaption_DateLastLogin_View' => 'Last Login Date',
	'_ml_pages_FieldCaption_DateLastEdit_View' => 'Last profile edition date',
	'_ml_pages_FieldCaption_General Info_Search' => 'Specific',
	'_ml_pages_FieldCaption_Couple_Search' => 'Profile type',
	'_ml_pages_FieldCaption_Sex_Search' => 'Looking for',
	'_ml_pages_FieldCaption_DateOfBirth_Search' => 'Aged',
	'_ml_pages_FieldCaption_Country_Search' => 'Country',
	'_ml_pages_FieldCaption_Keyword_Search' => 'Keyword',
	'_ml_pages_FieldCaption_Tags_Search' => 'Tag',
	'_ml_pages_FieldCaption_Location_Search' => 'Location',
		'_ml_pages_administration_fields' => 'Fields',
		'_ml_pages_create_now' => 'Create Now',
		'_ml_pages_create_page_success' => 'Page Successfully Created!',
		'_ml_pages_create_page_select_category' => 'Please select a page category',
		'_ml_pages_select' => '--Select--',
		'_ml_pages_create_page' => 'Create Page',
		'_ml_pages_edit_page' => 'Edit Page',
		'_ml_pages_view_page' => 'View Page',
		'_ml_pages_search_page' => 'Search Page',
		'_ml_pages_title' => 'Page Fields',
		'_ml_pages_allow_view_fans_to' => 'Allow views to',
		'_ml_pages_main_category' => 'Main Category',
		'_ml_pages_block_categories' => 'Category',
		'_ml_pages_block_author' => 'Author',
    '_sbs_txt_title_ml_pages' => 'Pages',
    '_ml_pages' => 'Pages',
    '_ml_pages_single' => 'page',
    '_ml_pages_plural' => 'pages',
    '_ml_pages_action_pages_home' => 'Pages Home',
    '_ml_pages_action_remove_from_featured' => 'Remove From Featured',
    '_ml_pages_action_add_to_featured' => 'Add To Featured',
    '_ml_pages_action_create_page' => 'Create Page',
    '_ml_pages_action_my_pages' => 'My Pages',
		'_ml_pages_action_title_delete' => 'Delete',
		'_ml_pages_action_title_edit' => 'Edit',
		'_ml_pages_action_title_privacy' => 'Privacy',
		'_ml_pages_action_title_invite' => 'Invite',
		'_ml_pages_action_title_leave' => 'Leave',
		'_ml_pages_action_title_join' => 'I\'m a fan',
    '_ml_pages_action_title_share' => 'Share',
    '_ml_pages_action_title_broadcast' => 'Broadcast',    
    '_ml_pages_action_manage_fans' => 'Manage fans',
    '_ml_pages_action_upload_photos' => 'Add Photos',
    '_ml_pages_action_upload_videos' => 'Add Videos',
    '_ml_pages_action_upload_sounds' => 'Add Sounds',
    '_ml_pages_action_upload_files' => 'Add Files',
    '_ml_pages_add_new_page_admin' => 'Create Page',
    '_ml_pages_user_unknown' => 'Unknown',
    '_ml_pages_admin' => 'admin',    
		'_ml_pages_admin_activate' => 'Activate',	
    '_ml_pages_admin_delete' => 'Delete',
    '_ml_pages_admin_pages' => 'Admin Pages',
    '_ml_pages_admin_home' => 'Home',
    '_ml_pages_administration' => 'Pages Administration',
    '_ml_pages_administration_create_page' => 'Create Page', 
    '_ml_pages_administration_settings' => 'Settings', 
    '_ml_pages_administration_admin_pages' => 'Admin Pages',
		'_ml_pages_all_countries' => 'All Countries',
		'_ml_pages_allow_comments_all' => 'All',
		'_ml_pages_allow_comments_friends' => 'Friends Only',
		'_ml_pages_allow_comments_none' => 'Nobody',
		'_ml_pages_allow_comments_fans' => 'Fans Only',
		'_ml_pages_allow_rate_all' => 'All',
		'_ml_pages_allow_rate_friends' => 'Friends Only',
		'_ml_pages_allow_rate_none' => 'Nobody',
		'_ml_pages_allow_rate_fans' => 'Fans Only',
	    '_ml_pages_calendar' => 'Calendar ',
    '_ml_pages_spy_post' => '<a href="{profile_link}">{profile_nick}</a> added new page <a href="{entry_url}">{entry_title}</a>',
    '_ml_pages_spy_post_change' => '<a href="{profile_link}">{profile_nick}</a> changed page <a href="{entry_url}">{entry_title}</a>',
    '_ml_pages_spy_join' => '<a href="{profile_link}">{profile_nick}</a> created page <a href="{entry_url}">{entry_title}</a>',
    '_ml_pages_spy_rate' => '<a href="{profile_link}">{profile_nick}</a> rated page <a href="{entry_url}">{entry_title}</a>',
    '_ml_pages_spy_comment' => '<a href="{profile_link}">{profile_nick}</a> commented on page <a href="{entry_url}">{entry_title}</a>',

    '_ml_pages_sbs_change' => 'information was updated',
    '_ml_pages_sbs_comment' => 'new comment arrived',
    '_ml_pages_sbs_rate' => 'rating was updated',
    '_ml_pages_sbs_join' => 'new participant',

		'_ml_pages_caption_add' => 'Create Page', 
		'_ml_pages_caption_allow_comments' => 'Allow to view and post comments',
		'_ml_pages_caption_allow_rate' => 'Allow rating',
		'_ml_pages_caption_allow_view_fans' => 'Allow viewinging fans',
		'_ml_pages_caption_author_id' => 'Author ID',
    '_ml_pages_caption_browse_by_author' => 'Browse Pages By Author: ',
    '_ml_pages_caption_browse_by_author_joined_pages' => 'Browse Author Created Pages: ',
    '_ml_pages_caption_browse_by_country' => 'Browse Pages By Country: ',
    '_ml_pages_caption_browse_by_category' => 'Browse Pages By Category: ',
    '_ml_pages_caption_browse_by_day' => 'Browse Pages By Day: ',
    '_ml_pages_caption_browse_by_tag' => 'Browse Pages By Tag: ',
    '_ml_pages_caption_browse_featured' => 'Featured Pages',
    '_ml_pages_caption_browse_popular' => 'Popular Pages',
    '_ml_pages_caption_browse_recently_added' => 'Recently Added Pages',
    '_ml_pages_caption_browse_top_rated' => 'Top Rated Pages',
    '_ml_pages_caption_browse_upcoming' => 'Upcoming Pages',
    '_ml_pages_caption_browse_past' => 'Past Pages',
		'_ml_pages_caption_city' => 'City',
		'_ml_pages_caption_country' => 'Country',
		'_ml_pages_caption_desc' => 'Description',
		'_ml_pages_caption_edit' => 'Edit Page',
		'_ml_pages_caption_privacy' => 'Page Privacy',
		'_ml_pages_caption_page_end' => 'Date end',
		'_ml_pages_caption_page_start' => 'Date start',
		'_ml_pages_caption_invite' => 'Send Invitation To ',
		'_ml_pages_caption_join_filter' => 'Allow to join',
		'_ml_pages_caption_keyword' => 'Keyword',
		'_ml_pages_caption_membership_filter' => 'Allow joining by membership',
		'_ml_pages_caption_photo' => 'Photo',
		'_ml_pages_caption_place' => 'Place name',
    '_ml_pages_caption_search' => 'Search',
    '_ml_pages_caption_search_results' => 'Search Results:',
		'_ml_pages_caption_title' => 'Title',	
    '_ml_pages_caption_share_page' => 'Share',
    '_ml_pages_caption_videos' => 'Videos',
    '_ml_pages_caption_photos' => 'Photos',
    '_ml_pages_caption_sounds' => 'Sounds',
    '_ml_pages_caption_files' => 'Files',
    '_ml_pages_caption_comments' => 'Comments',
    '_ml_pages_caption_fans' => 'Fans',
    '_ml_pages_caption_broadcast' => 'Broadcast message to page\'s fans',
    '_ml_pages_caption_manage_fans' => 'Manage Fans',
    '_ml_pages_caption_upload_photos' => 'Add Photos',
    '_ml_pages_caption_upload_videos' => 'Add Videos',
    '_ml_pages_caption_upload_sounds' => 'Add Sounds',
    '_ml_pages_caption_upload_files' => 'Add Files',

		'_ml_pages_err_allow_comments' => 'incorrect value',
		'_ml_pages_err_allow_rate' => 'incorrect value',
		'_ml_pages_err_allow_view_fans' => 'incorrect value',
		'_ml_pages_err_city' => 'please fill in city name',
		'_ml_pages_err_country' => 'please specify country',
		'_ml_pages_err_desc' => 'please specify description from 20 characters',
		'_ml_pages_err_page_end' => 'date format is incorrect',
		'_ml_pages_err_page_start' => 'date format is incorrect',
		'_ml_pages_err_join_filter' => 'incorrect value',
		'_ml_pages_err_keyword' => 'please specify keyword from 3 to 100 characters',
		'_ml_pages_err_membership_filter' => 'incorrect value',
		'_ml_pages_err_photo' => 'please select a photo',
		'_ml_pages_err_place' => 'this is a required field',
		'_ml_pages_err_tags' => 'please enter at least one word which describes this page',
		'_ml_pages_err_title' => 'please specify title from 3 to 100 characters',
    '_ml_pages_error_occured' => 'Error Occurred',

    '_ml_pages_form_header_info' => 'Page\'s Info',
    '_ml_pages_form_header_privacy' => 'Page\'s Privacy Settings',

    '_ml_pages_form_caption_file_title' => 'Title:',
    '_ml_pages_form_header_images' => 'Page\'s Photos',
    '_ml_pages_form_caption_thumb_choice' => 'Choose thumbnail',
    '_ml_pages_form_info_thumb_choice' => 'You can choose any uploaded image as page thumnail',
    '_ml_pages_form_caption_images_choice' => 'Choose',
    '_ml_pages_form_info_images_choice' => 'Unchecked images will be deleted',
    '_ml_pages_form_caption_images_upload' => 'Upload',
    '_ml_pages_form_info_images_upload' => 'Image will be placed in the "Pages" category automatically',

    '_ml_pages_form_header_videos' => 'Page\'s Videos',
    '_ml_pages_form_caption_videos_choice' => 'Choose',
    '_ml_pages_form_info_videos_choice' => 'Unchecked videos will be deleted',
    '_ml_pages_form_caption_videos_upload' => 'Upload',
    '_ml_pages_form_info_videos_upload' => 'Video will be placed in the "Pages" category automatically',

    '_ml_pages_form_header_sounds' => 'Page\'s Sounds',
    '_ml_pages_form_caption_sounds_choice' => 'Choose',
    '_ml_pages_form_info_sounds_choice' => 'Unchecked sounds will be deleted',
    '_ml_pages_form_caption_sounds_upload' => 'Upload',
    '_ml_pages_form_info_sounds_upload' => 'Sound will be placed in the "Pages" category automatically',

    '_ml_pages_form_header_files' => 'Page\'s Files',
    '_ml_pages_form_caption_files_choice' => 'Choose',
    '_ml_pages_form_info_files_choice' => 'Unchecked files will be deleted',
    '_ml_pages_form_caption_files_upload' => 'Upload',
    '_ml_pages_form_info_files_upload' => 'File will be placed in the "Pages" category automatically',

    '_ml_pages_form_caption_broadcast_title' => 'Broadcast Title',
    '_ml_pages_form_err_broadcast_title' => 'Please enter from 3 to 100 characters',
    '_ml_pages_form_caption_broadcast_message' => 'Broadcast Message',
    '_ml_pages_form_err_broadcast_message' => 'Please enter at least 10 characters',

    '_ml_pages_form_caption_join_confirmation' => 'Join confirmation',
    '_ml_pages_form_info_join_confirmation' => 'If enabled, page admin(s) will have to confirm each user before he/she becomes a participant.',
    '_ml_pages_form_join_confirmation_disabled' => 'Disabled',
    '_ml_pages_form_join_confirmation_enabled' => 'Enabled',

    '_ml_pages_page_join_success' => 'You have successfully created this page',
    '_ml_pages_page_joined_already' => 'You have already created this page',
    '_ml_pages_page_join_success_pending' => 'You have successfully created this page, please wait while your request is reviewed by page admin(s)',
    '_ml_pages_page_joined_already_pending' => 'Your join request is pending approval.',    
		'_ml_pages_page_leave_success' => 'You have successfully left this page',
		'_ml_pages_page_was_deleted' => 'Page was deleted',	
		'_ml_pages_info_allow_comments' => 'only these members will be able to view and post comments',
		'_ml_pages_info_allow_rete' => 'only these members will be able to rate the page',
    '_ml_pages_info_allow_view_fans' => 'only these members will be able to view the fans list',
    '_ml_pages_info_author' => 'you can see profile\\\'s ID in admin panel member\\\'s list',
		'_ml_pages_info_join_filter' => 'only these members will be able to join this page',	
    '_ml_pages_info_membership_filter' => 'only these members will be able to join this page',
    '_ml_pages_invitation_sent' => '%d invitations have been sent',

		'_ml_pages_join_all' => 'All',
		'_ml_pages_join_friends_only' => 'Friends Only',
		'_ml_pages_main' => 'Pages',
    '_ml_pages_membership_filter_none' => 'Allow All',	
		'_ml_pages_msg_access_denied' => 'Access Denied',
		'_ml_pages_msg_page_not_found' => 'Page Not Found',
    '_ml_pages_msg_pending_approval' => 'This page is pending administrator approval. Please, wait.',
    '_ml_pages_msg_added_to_featured' => 'Page was added to featured',
    '_ml_pages_msg_removed_from_featured' => 'Page was removed from featured',
    '_ml_pages_msg_you_have_pending_approval_pages' => 'You have <a href="%s">%d pending approval pages</a>',
    '_ml_pages_msg_you_have_no_pages' => 'You have not added any pages. <a href="%s">Click here</a> to add one.',
    '_ml_pages_msg_you_have_some_pages' => 'You have <a href="%s">%d page(s)</a>. <a href="%s">Click here</a> to add more.',
    '_ml_pages_msg_broadcast_no_fans' => 'This page has no fans yet',
    '_ml_pages_msg_broadcast_message_sent' => 'Broadcast message has been successfully sent',
		'_ml_pages_no_users_msg' => 'There are no users in your contacts',
		'_ml_pages_pending_approval' => 'Pending Approval',
		'_ml_pages_photo_is_pending_approval' => 'Photo is pending approval. Please be patient.',	
		'_ml_pages_settings_admin' => 'Settings',

    '_ml_pages_privacy_view_page' => 'View Page',
    '_ml_pages_privacy_join' => 'Allow joining',
    '_ml_pages_privacy_comment' => 'Allow to view and post comments',
    '_ml_pages_privacy_rate' => 'Allow rating',
    '_ml_pages_privacy_view_fans' => 'Allow viewing fans',
    '_ml_pages_privacy_post_in_forum' => 'Allow posting in forum',
    '_ml_pages_privacy_fans_only' => 'Fans only',    
    '_ml_pages_privacy_fans' => 'Fans',    
    '_ml_pages_privacy_admins_only' => 'Admins Only',
    '_ml_pages_privacy_upload_photos' => 'Upload Photos',
    '_ml_pages_privacy_upload_videos' => 'Upload Videos',
    '_ml_pages_privacy_upload_sounds' => 'Upload Sounds',
    '_ml_pages_privacy_upload_files' => 'Upload Files',    

    '_ml_pages_tags' => 'Pages Tags',
    '_ml_pages_categories' => 'Pages Categories',
		'_ml_pages_view_fans_all' => 'All',
		'_ml_pages_view_fans_friends' => 'Friends Only',
		'_ml_pages_view_fans_none' => 'Nobody',    

    '_ml_pages_block_actions' => 'Actions',
    '_ml_pages_block_info' => 'Information',
    '_ml_pages_block_desc' => 'Description',
    '_ml_pages_block_fans' => 'Fans',
    '_ml_pages_block_fans_unconfirmed' => 'Unconfirmed Fans',
    '_ml_pages_block_photos' => 'Photos',
    '_ml_pages_block_videos' => 'Videos',
    '_ml_pages_block_sounds' => 'Sounds',
    '_ml_pages_block_files' => 'Files',
    '_ml_pages_block_rate' => 'Rate',
    '_ml_pages_block_comments' => 'Comments',
    '_ml_pages_block_calendar' => 'Pages Calendar ',
    '_ml_pages_block_upcoming_photo' => 'Upcoming Public Page',
    '_ml_pages_block_upcoming_list' => 'Upcoming Public Pages',
    '_ml_pages_block_past_list' => 'Past Public Pages',
    '_ml_pages_block_recently_added_list' => 'Recently Added Public Pages',
    '_ml_pages_block_my_pages' => 'My Pages',
		'_ml_pages_block_joined_pages' => 'Created Pages',
    '_ml_pages_block_administration' => 'Administration',
    '_ml_pages_block_user_pages' => 'My Pages',
    '_ml_pages_block_home' => 'Public Pages',

    '_ml_pages_block_submenu_main' => 'Main',
    '_ml_pages_block_submenu_add' => 'Add',
    '_ml_pages_block_submenu_manage' => 'Manage',
    '_ml_pages_block_submenu_pending' => 'Pending Approval',

    '_ml_pages_menu_root' => 'Pages',
    '_ml_pages_menu_main' => 'Pages Home',
    '_ml_pages_menu_upcoming_pages' => 'Upcoming',
    '_ml_pages_menu_past_pages' => 'Past',
    '_ml_pages_menu_recently_added' => 'Recently Added',
    '_ml_pages_menu_featured' => 'Featured',
    '_ml_pages_menu_my_pages' => 'My Pages',
    '_ml_pages_menu_my_pages_profile' => 'Pages',
    '_ml_pages_menu_my_pending_pages' => 'Pending Approval',
    '_ml_pages_menu_calendar' => 'Calendar',
    '_ml_pages_menu_popular' => 'Popular',
    '_ml_pages_menu_search' => 'Search',
    '_ml_pages_menu_tags' => 'Tags',
    '_ml_pages_menu_categories' => 'Categories',
    '_ml_pages_menu_top_rated' => 'Top Rated',
    '_ml_pages_menu_add' => 'Create Page',
    '_ml_pages_menu_view' => 'Main',
    '_ml_pages_menu_view_forum' => 'Forum',
    '_ml_pages_menu_view_comments' => 'Comments',
    '_ml_pages_menu_view_fans' => 'Fans',
    '_ml_pages_menu_view_photos' => 'Photos',
    '_ml_pages_menu_view_videos' => 'Videos',
    '_ml_pages_menu_view_sounds' => 'Sounds',
    '_ml_pages_menu_view_files' => 'Files',

    '_ml_pages_tab_recent' => 'Recently Added',
    '_ml_pages_tab_upcoming' => 'Upcoming',
    '_ml_pages_tab_featured' => 'Featured',
    '_ml_pages_tab_top' => 'Top',
    '_ml_pages_tab_popular' => 'Popular',

    '_ml_pages_wall_added_new' => 'added new',
    '_ml_pages_wall_object' => 'page',

    '_ml_pages_announce' => 'announce',

    '_ml_pages_view' => 'pages view', 
    '_ml_pages_browse' => 'pages browse', 
    '_ml_pages_search' => 'pages search', 
    '_ml_pages_add' => 'pages add', 
    '_ml_pages_comments_delete_and_edit' => 'pages comments delete and edit', 
    '_ml_pages_edit_any_page' => 'pages edit any page', 
    '_ml_pages_delete_any_page' => 'pages delete any page', 
    '_ml_pages_mark_as_featured' => 'pages marked as featured', 
    '_ml_pages_approve' => 'pages approve', 
    '_ml_pages_broadcast_message' => 'pages broadcast message',
    '_ml_pages_block_misc' => 'Misc Info',
);

?>
